export const colors = {
  background: "var(--sl-bg)",
  foreground: "var(--sl-ink)",
  secondary: "var(--sl-muted)",
  tertiary: "var(--sl-faint)",
  divider: "var(--sl-line)",
  hover: "var(--sl-hover)",
  surface: "var(--sl-surface)",
  accent: "var(--sl-accent)",
  accentLight: "var(--sl-accent-weak)",

  backgroundDark: "var(--sl-bg)",
  foregroundDark: "var(--sl-ink)",
  secondaryDark: "var(--sl-muted)",
  tertiaryDark: "var(--sl-faint)",
  dividerDark: "var(--sl-line)",
  hoverDark: "var(--sl-hover)",
  surfaceDark: "var(--sl-surface)",
  accentDark: "var(--sl-accent)",
  accentLightDark: "var(--sl-accent-weak)",

  officeBlue: "var(--sl-blue)",
  officeBlueLight: "color-mix(in srgb, var(--sl-blue) 12%, transparent)",
  officeBlueMuted: "color-mix(in srgb, var(--sl-blue) 20%, transparent)",
  aiViolet: "var(--sl-violet)",
  aiVioletLight: "color-mix(in srgb, var(--sl-violet) 12%, transparent)",
  aiVioletMuted: "color-mix(in srgb, var(--sl-violet) 20%, transparent)",

  warning: "var(--sl-amber)",
  error: "var(--sl-red)",
  info: "var(--sl-muted)",
  success: "var(--sl-green)",

  gray50: "var(--sl-bg)",
  gray100: "var(--sl-surface-2)",
  gray200: "var(--sl-line)",
  gray300: "var(--sl-line)",
  gray400: "var(--sl-faint)",
  gray500: "var(--sl-muted)",
  gray600: "var(--sl-muted)",
  gray700: "var(--sl-ink)",
  gray800: "var(--sl-ink)",
  gray900: "var(--sl-ink)",
} as const;

export type ColorToken = keyof typeof colors;
