/**
 * Action catalogue for XLSX. Single source of truth tying together
 * each command-bus handler, its CLI subcommand, and its Cmd+K palette
 * entry.
 *
 * Seeded mechanically from `packages/agent/src/cli-xlsx.ts` and
 * `apps/web/app/xlsx-editor/XlsxEditor.tsx`. Add new public actions
 * HERE first; the parity check refuses to land a handler with no
 * catalogue entry.
 *
 * Notes on `cliKind`:
 *   - "dispatch" (default): The CLI adapter generates a subcommand
 *     that loads the workbook, dispatches `commandType` with the
 *     payload built by `buildPayload`, and writes the result. Common
 *     write flags (`--source`, `--agent-id`, `--no-approve`, `--out`,
 *     `--pretty`) are added automatically.
 *   - "custom": Hand-rolled commander block in `cli-xlsx.ts` retains
 *     ownership (custom batch logic, stdin handling, multi-step
 *     pipelines). The catalogue still owns the label/description and
 *     the parity check verifies a subcommand by that name exists.
 */

import type { ActionDescriptor } from "@officeai/core";

export const xlsxActions: ReadonlyArray<ActionDescriptor> = [
  // ── File / Read (no commandType — they don't mutate) ──────────────
  {
    id: "xlsx.create",
    commandType: null,
    label: "Create blank workbook",
    description: "Create a brand-new blank .xlsx file at --out (one empty worksheet named Sheet1).",
    section: "File",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.inspect",
    commandType: null,
    label: "Inspect workbook",
    description: "Print a structural summary (sheets, cells, parts, comments, merges) as JSON.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.read",
    commandType: null,
    label: "Read sheet / range",
    description: "Render a sheet (or range) as Markdown or JSON.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.search",
    commandType: null,
    label: "Search workbook",
    description: "Search workbook cells for text and print matches as JSON.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.diff",
    commandType: null,
    label: "Diff workbooks",
    description: "Compute a structural diff between two on-disk .xlsx files.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.apply-file",
    commandType: null,
    label: "Apply JSON commands",
    description: "Apply a JSON command file (single command or { commands: [...] }) and write the result.",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.apply",
    commandType: null,
    label: "Apply raw command",
    description:
      "Generic command escape hatch — pass --type and --payload (JSON), or --type with --payload-stdin.",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.fill-formula",
    commandType: null,
    label: "Fill formula across range",
    description:
      "Fill a formula across an A1 range, expanding {row}/{col}/{rowN}/{colN} placeholders per cell.",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.clear-range",
    commandType: null,
    label: "Clear range",
    description: "Wipe every cell in an A1 range to null in a single round-trip.",
    section: "Edit",
    surfaces: ["cli"],
  },

  // ── Cell value / formula / format ─────────────────────────────────
  {
    id: "xlsx.set-cell",
    commandType: "xlsx:set-cell-value",
    label: "Set cell value",
    description: "Set a single cell's literal value (string/number/boolean/null/error).",
    section: "Edit",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.set-formula",
    commandType: "xlsx:set-cell-formula",
    label: "Set formula",
    description: "Set a single cell's formula (with or without leading '=').",
    section: "Edit",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.set-range",
    commandType: "xlsx:set-range-values",
    label: "Set range values",
    description: "Set a row-major 2-D matrix of cell values across a range.",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.set-format",
    commandType: "xlsx:set-cell-format",
    label: "Apply cell format",
    description: "Apply a format patch to a range (font/fill/border/alignment/numberFormat).",
    section: "Format",
    surfaces: ["cli", "palette"],
  },

  // ── Sheet management ──────────────────────────────────────────────
  {
    id: "xlsx.add-sheet",
    commandType: "xlsx:add-sheet",
    label: "Add sheet",
    description: "Append (or insert at --at) a new worksheet.",
    section: "Sheet",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.rename-sheet",
    commandType: "xlsx:rename-sheet",
    label: "Rename sheet",
    description: "Rename a sheet by current name.",
    section: "Sheet",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.delete-sheet",
    commandType: "xlsx:delete-sheet",
    label: "Delete sheet",
    description: "Delete a worksheet by name (the workbook must keep ≥1 visible sheet).",
    section: "Sheet",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.move-sheet",
    commandType: "xlsx:move-sheet",
    label: "Move sheet",
    description: "Reorder a sheet within the workbook.",
    section: "Sheet",
    surfaces: ["palette"],
    hidden: { reason: "Reachable via the sheet tabs context menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.set-sheet-state",
    commandType: "xlsx:set-sheet-state",
    label: "Set sheet visibility",
    description: "Hide / show / very-hide a worksheet.",
    section: "Sheet",
    surfaces: ["palette"],
    hidden: { reason: "Reachable via the sheet tabs context menu; CLI exposure is deferred." },
  },

  // ── Rows / columns / merges ───────────────────────────────────────
  {
    id: "xlsx.insert-row",
    commandType: "xlsx:insert-row",
    label: "Insert rows",
    description: "Insert N blank rows BEFORE a 1-based row index.",
    section: "Edit",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.insert-column",
    commandType: "xlsx:insert-column",
    label: "Insert columns",
    description: "Insert N blank columns BEFORE a 1-based column index.",
    section: "Edit",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.delete-row",
    commandType: "xlsx:delete-row",
    label: "Delete rows",
    description: "Delete N rows starting at a 1-based row index.",
    section: "Edit",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.delete-column",
    commandType: "xlsx:delete-column",
    label: "Delete columns",
    description: "Delete N columns starting at a 1-based column index.",
    section: "Edit",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.merge-cells",
    commandType: "xlsx:merge-cells",
    label: "Merge cells",
    description: "Merge an A1 range covering ≥2 cells.",
    section: "Format",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.unmerge-cells",
    commandType: "xlsx:unmerge-cells",
    label: "Unmerge cells",
    description: "Unmerge an existing merged range (must match exactly).",
    section: "Format",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.set-column-width",
    commandType: "xlsx:set-column-width",
    label: "Set column width",
    description: "Override a column's width in CSS pixels.",
    section: "Format",
    surfaces: ["cli"],
  },
  {
    id: "xlsx.set-row-height",
    commandType: "xlsx:set-row-height",
    label: "Set row height",
    description: "Override a row's height in CSS pixels.",
    section: "Format",
    surfaces: ["cli"],
  },

  // ── Comments / notes ──────────────────────────────────────────────
  {
    id: "xlsx.add-comment",
    commandType: "xlsx:add-comment",
    label: "Add comment",
    description: "Attach a classic note (single-cell anchor).",
    section: "Comments",
    surfaces: ["cli", "palette"],
  },
  {
    id: "xlsx.reply-comment",
    commandType: "xlsx:reply-comment",
    label: "Reply to comment",
    description: "Append a reply to an existing comment thread.",
    section: "Comments",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the comment thread UI; CLI exposure is deferred." },
  },
  {
    id: "xlsx.resolve-comment",
    commandType: "xlsx:resolve-comment",
    label: "Resolve comment",
    description: "Mark a comment as resolved.",
    section: "Comments",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the comment thread UI; CLI exposure is deferred." },
  },
  {
    id: "xlsx.edit-comment",
    commandType: "xlsx:edit-comment",
    label: "Edit comment",
    description: "Edit a comment's text.",
    section: "Comments",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the comment thread UI; CLI exposure is deferred." },
  },
  {
    id: "xlsx.delete-comment",
    commandType: "xlsx:delete-comment",
    label: "Delete comment",
    description: "Delete a comment thread.",
    section: "Comments",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the comment thread UI; CLI exposure is deferred." },
  },

  // ── Conditional formatting / validation / defined names ───────────
  {
    id: "xlsx.add-conditional-format",
    commandType: "xlsx:add-conditional-format",
    label: "Add conditional format",
    description: "Add a conditional formatting rule to a range.",
    section: "Format",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the conditional-formatting dialog; CLI exposure is deferred." },
  },
  {
    id: "xlsx.remove-conditional-format",
    commandType: "xlsx:remove-conditional-format",
    label: "Remove conditional format",
    description: "Remove a conditional formatting rule.",
    section: "Format",
    surfaces: [],
    hidden: { reason: "Companion to add-conditional-format; not surfaced standalone." },
  },
  {
    id: "xlsx.clear-conditional-formats",
    commandType: "xlsx:clear-conditional-formats",
    label: "Clear conditional formats",
    description: "Drop every conditional formatting rule from a sheet.",
    section: "Format",
    surfaces: [],
    hidden: { reason: "Reached via the conditional-formatting dialog; CLI exposure is deferred." },
  },
  {
    id: "xlsx.add-data-validation",
    commandType: "xlsx:add-data-validation",
    label: "Add data validation",
    description: "Add a data validation rule to a range.",
    section: "Data",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the data-validation dialog; CLI exposure is deferred." },
  },
  {
    id: "xlsx.remove-data-validation",
    commandType: "xlsx:remove-data-validation",
    label: "Remove data validation",
    description: "Remove a data validation rule.",
    section: "Data",
    surfaces: [],
    hidden: { reason: "Companion to add-data-validation." },
  },
  {
    id: "xlsx.clear-data-validations",
    commandType: "xlsx:clear-data-validations",
    label: "Clear data validations",
    description: "Drop every data validation rule on a sheet.",
    section: "Data",
    surfaces: [],
    hidden: { reason: "Reached via the data-validation dialog." },
  },
  {
    id: "xlsx.add-defined-name",
    commandType: "xlsx:add-defined-name",
    label: "Add defined name",
    description: "Define a workbook- or sheet-scoped name.",
    section: "Data",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the name-manager dialog; CLI exposure is deferred." },
  },
  {
    id: "xlsx.update-defined-name",
    commandType: "xlsx:update-defined-name",
    label: "Update defined name",
    description: "Update an existing defined name's reference or scope.",
    section: "Data",
    surfaces: [],
    hidden: { reason: "Reached via the name-manager dialog." },
  },
  {
    id: "xlsx.remove-defined-name",
    commandType: "xlsx:remove-defined-name",
    label: "Remove defined name",
    description: "Delete a defined name.",
    section: "Data",
    surfaces: [],
    hidden: { reason: "Reached via the name-manager dialog." },
  },

  // ── Tables / charts / images ──────────────────────────────────────
  {
    id: "xlsx.add-table",
    commandType: "xlsx:add-table",
    label: "Add table",
    description: "Convert a range into a structured table (with auto-filter and styles).",
    section: "Insert",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the Insert ▸ Table menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.remove-table",
    commandType: "xlsx:remove-table",
    label: "Remove table",
    description: "Convert a structured table back to a plain range.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via the table context menu." },
  },
  {
    id: "xlsx.add-chart",
    commandType: "xlsx:add-chart",
    label: "Insert chart",
    description: "Insert a chart anchored to a sheet position.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "BarChart3",
    hidden: { reason: "Reached via the Insert ▸ Chart menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.remove-chart",
    commandType: "xlsx:remove-chart",
    label: "Remove chart",
    description: "Remove an inserted chart.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via the chart context menu." },
  },
  {
    id: "xlsx.move-chart",
    commandType: "xlsx:move-chart",
    label: "Move chart",
    description: "Reposition a chart on the sheet.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via chart drag handles." },
  },
  {
    id: "xlsx.resize-chart",
    commandType: "xlsx:resize-chart",
    label: "Resize chart",
    description: "Resize a chart on the sheet.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via chart resize handles." },
  },
  {
    id: "xlsx.update-chart",
    commandType: "xlsx:update-chart",
    label: "Update chart",
    description:
      "Patch a chart's type, data range, header/category toggles, title, palette, legend/data-label/gridline toggles, or axis titles.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via the chart toolbar / Edit chart dialog." },
  },
  {
    id: "xlsx.add-image",
    commandType: "xlsx:add-image",
    label: "Insert image",
    description: "Insert an image anchored to a sheet position.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "Image",
    hidden: { reason: "Reached via the Insert ▸ Image menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.move-image",
    commandType: "xlsx:move-image",
    label: "Move image",
    description: "Reposition an image on the sheet.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via image drag handles." },
  },
  {
    id: "xlsx.resize-image",
    commandType: "xlsx:resize-image",
    label: "Resize image",
    description: "Resize an image on the sheet.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via image resize handles." },
  },
  {
    id: "xlsx.remove-image",
    commandType: "xlsx:remove-image",
    label: "Remove image",
    description: "Remove an image from the sheet.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via image context menu." },
  },

  // ── Auto-filter / sort / paste / fill / freeze / split ────────────
  {
    id: "xlsx.set-auto-filter",
    commandType: "xlsx:set-auto-filter",
    label: "Set auto-filter",
    description: "Apply an auto-filter to a range.",
    section: "Data",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the Data ▸ Filter menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.set-filter-column",
    commandType: "xlsx:set-filter-column",
    label: "Filter column",
    description: "Configure a column filter inside an existing auto-filter.",
    section: "Data",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the column filter dropdown." },
  },
  {
    id: "xlsx.clear-filter-column",
    commandType: "xlsx:clear-filter-column",
    label: "Clear column filter",
    description: "Clear the filter on a single column.",
    section: "Data",
    surfaces: [],
    hidden: { reason: "Reached via the column filter dropdown." },
  },
  {
    id: "xlsx.sort-range",
    commandType: "xlsx:sort-range",
    label: "Sort range",
    description: "Sort a range by one or more keys.",
    section: "Data",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the Data ▸ Sort menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.paste-range",
    commandType: "xlsx:paste-range",
    label: "Paste range",
    description: "Paste a 2-D matrix of values into a sheet.",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via clipboard paste; not surfaced standalone." },
  },
  {
    id: "xlsx.text-to-columns",
    commandType: "xlsx:text-to-columns",
    label: "Text to columns",
    description: "Split a column's text into multiple columns by delimiter.",
    section: "Data",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the Data ▸ Text to columns dialog; CLI exposure is deferred." },
  },
  {
    id: "xlsx.fill-range",
    commandType: "xlsx:fill-range",
    label: "Fill range",
    description: "Fill a range with a series (linear/growth/date/etc).",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via the autofill drag handle." },
  },
  {
    id: "xlsx.freeze-panes",
    commandType: "xlsx:freeze-panes",
    label: "Freeze panes",
    description: "Freeze rows / columns above and to the left of a cell.",
    section: "View",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the View ▸ Freeze menu; CLI exposure is deferred." },
  },
  {
    id: "xlsx.unfreeze-panes",
    commandType: "xlsx:unfreeze-panes",
    label: "Unfreeze panes",
    description: "Remove all frozen-pane splits on a sheet.",
    section: "View",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the View ▸ Freeze menu; CLI exposure is deferred." },
  },

  // ── Palette-only convenience entries (UI wrappers / dialogs) ──────
  // Each entry is reachable from Cmd+K via the editor's runner map.
  // commandType is null when the action is sugar (toggles, dialogs)
  // around a richer catalogue entry; the CLI exposes the underlying
  // verb separately.
  {
    id: "xlsx.toggle-filter",
    commandType: null,
    label: "Toggle auto-filter",
    description: "Apply or remove an auto-filter on the active sheet.",
    section: "Data",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-cells",
    commandType: null,
    label: "Format cells…",
    description: "Open the Format Cells dialog (Number tab).",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-cells-alignment",
    commandType: null,
    label: "Format cells: Alignment",
    description: "Open the Format Cells dialog on the Alignment tab.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-cells-font",
    commandType: null,
    label: "Format cells: Font",
    description: "Open the Format Cells dialog on the Font tab.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-cells-border",
    commandType: null,
    label: "Format cells: Border",
    description: "Open the Format Cells dialog on the Border tab.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-cells-fill",
    commandType: null,
    label: "Format cells: Fill",
    description: "Open the Format Cells dialog on the Fill tab.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-cells-protection",
    commandType: null,
    label: "Format cells: Protection",
    description: "Open the Format Cells dialog on the Protection tab.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.borders-all",
    commandType: null,
    label: "Borders: All",
    description: "Apply borders to every cell in the selection.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.borders-outside",
    commandType: null,
    label: "Borders: Outside",
    description: "Apply borders only to the perimeter of the selection.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.borders-thick-outside",
    commandType: null,
    label: "Borders: Thick outside",
    description: "Apply a thick border to the perimeter of the selection.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.borders-none",
    commandType: null,
    label: "Borders: Clear",
    description: "Remove all borders from the selection.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.paste-special",
    commandType: null,
    label: "Paste Special…",
    description: "Open the Paste Special dialog.",
    section: "Edit",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-painter",
    commandType: null,
    label: "Format Painter",
    description: "Activate the Format Painter to copy cell formatting.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.hide-sheet",
    commandType: null,
    label: "Hide sheet",
    description: "Hide the active sheet (preserves data; toggle via the sheet tab menu).",
    section: "Sheet",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.conditional-format",
    commandType: null,
    label: "Conditional Formatting…",
    description: "Open the Conditional Formatting manager dialog.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.conditional-format-clear",
    commandType: null,
    label: "Clear conditional formatting from this sheet",
    description: "Drop every conditional-formatting rule on the active sheet.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.data-validation",
    commandType: null,
    label: "Data Validation…",
    description: "Open the Data Validation dialog for the active selection.",
    section: "Data",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.data-validation-clear",
    commandType: null,
    label: "Clear data validation from this sheet",
    description: "Drop every data-validation rule on the active sheet.",
    section: "Data",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.name-manager",
    commandType: null,
    label: "Name Manager…",
    description: "Open the Name Manager dialog to inspect and edit defined names.",
    section: "Data",
    surfaces: ["palette"],
    shortcut: "F3",
  },
  {
    id: "xlsx.define-name",
    commandType: null,
    label: "Define name from selection…",
    description: "Open the Name Manager scoped to the current selection.",
    section: "Data",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.merge",
    commandType: null,
    label: "Merge cells",
    description: "Merge the current selection into one cell.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.unmerge",
    commandType: null,
    label: "Unmerge cells",
    description: "Split previously merged cells in the current selection.",
    section: "Format",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.insert-image",
    commandType: null,
    label: "Insert image",
    description: "Pick and insert an image anchored to the active selection.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.format-as-table",
    commandType: null,
    label: "Format as Table…",
    description: "Convert the current selection into a structured table.",
    section: "Insert",
    surfaces: ["palette"],
    shortcut: "Mod+T",
  },
  {
    id: "xlsx.insert-chart",
    commandType: null,
    label: "Insert chart…",
    description: "Open the Insert Chart dialog for the current selection.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.insert-pivot-table",
    commandType: null,
    label: "Insert pivot table…",
    description:
      "Summarise the current selection by grouping a column and aggregating another. Result writes as plain values (full OOXML pivot round-trip lands in a follow-up).",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "xlsx.edit-chart",
    commandType: null,
    label: "Edit chart…",
    description: "Edit the currently selected chart's data range, type, and title.",
    section: "Insert",
    surfaces: ["palette"],
  },
];
