/**
 * Action catalogue for PPTX. Single source of truth tying together
 * each command-bus handler, its CLI subcommand, and its Cmd+K palette
 * entry.
 *
 * Seeded mechanically from `packages/agent/src/pptx-cli.ts` and
 * `apps/web/app/pptx-editor/PptxEditor.tsx`. Add new public actions
 * HERE first; the parity check refuses to land a handler with no
 * catalogue entry.
 */

import type { ActionDescriptor } from "@officeai/core";

export const pptxActions: ReadonlyArray<ActionDescriptor> = [
  // ── Read / file ───────────────────────────────────────────────────
  {
    id: "pptx.create",
    commandType: null,
    label: "Create blank presentation",
    description: "Create a brand-new blank .pptx file at --out (one empty slide on a default Blank layout).",
    section: "File",
    surfaces: ["cli"],
  },
  {
    id: "pptx.inspect",
    commandType: null,
    label: "Inspect presentation",
    description: "Print a structural summary (slides, shapes, masters, layouts) as JSON.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "pptx.read",
    commandType: null,
    label: "Read presentation",
    description: "Read a PPTX file as Markdown, structured JSON, or plain text.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "pptx.search",
    commandType: null,
    label: "Search presentation",
    description: "Search every slide's text content; emits matches as JSON.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "pptx.diff",
    commandType: null,
    label: "Diff presentations",
    description: "Compute a structural diff between two on-disk .pptx files.",
    section: "Read",
    surfaces: ["cli"],
  },
  {
    id: "pptx.apply",
    commandType: null,
    label: "Apply JSON commands",
    description: "Apply a JSON command file (single command or { commands: [...] }) and write the result.",
    section: "Edit",
    surfaces: ["cli"],
  },

  // ── Slide management ──────────────────────────────────────────────
  {
    id: "pptx.add-slide",
    commandType: "pptx:add-slide",
    label: "Add slide",
    description: "Append (or insert at --at) a new slide.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.delete-slide",
    commandType: "pptx:delete-slide",
    label: "Delete slide",
    description: "Delete a slide by 0-based index.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.duplicate-slide",
    commandType: "pptx:duplicate-slide",
    label: "Duplicate slide",
    description: "Duplicate a slide; the copy is inserted directly after the source.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.move-slide",
    commandType: "pptx:move-slide",
    label: "Move slide",
    description: "Reorder a slide.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.set-slide-layout",
    commandType: "pptx:set-slide-layout",
    label: "Set slide layout",
    description: "Reassign a slide's layout.",
    section: "Slide",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the slide context menu; CLI exposure is deferred." },
  },
  {
    id: "pptx.set-slide-notes",
    commandType: "pptx:set-slide-notes",
    label: "Edit speaker notes",
    description: "Set / replace a slide's speaker notes.",
    section: "Slide",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the notes pane; CLI exposure is deferred." },
  },
  {
    id: "pptx.set-slide-transition",
    commandType: "pptx:set-slide-transition",
    label: "Set slide transition",
    description: "Set the entry transition for a slide.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },

  // ── Text shapes ───────────────────────────────────────────────────
  {
    id: "pptx.set-text",
    commandType: "pptx:set-text",
    label: "Set shape text",
    description: "Replace the plain text of a text-bearing shape.",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "pptx.set-title",
    commandType: "pptx:set-text",
    label: "Set slide title",
    description: "Replace the slide's title placeholder text.",
    section: "Edit",
    surfaces: ["cli"],
    hidden: { reason: "Convenience wrapper around pptx:set-text targeting the title placeholder; same handler." },
  },
  {
    id: "pptx.set-body",
    commandType: "pptx:set-text",
    label: "Set slide body",
    description: "Replace the slide's body placeholder text.",
    section: "Edit",
    surfaces: ["cli"],
    hidden: { reason: "Convenience wrapper around pptx:set-text targeting the body placeholder; same handler." },
  },
  {
    id: "pptx.format-text",
    commandType: "pptx:format-text",
    label: "Format text run",
    description: "Apply font / size / bold / italic / underline / color to a text run range.",
    section: "Format",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.set-paragraph-alignment",
    commandType: "pptx:set-paragraph-alignment",
    label: "Set paragraph alignment",
    description: "Set paragraph alignment (left/center/right/justify) on a shape's paragraphs.",
    section: "Format",
    surfaces: ["cli"],
  },
  {
    id: "pptx.set-text-anchor",
    commandType: "pptx:set-text-anchor",
    label: "Set text anchor",
    description: "Set vertical text anchor (top/middle/bottom) on a shape's body.",
    section: "Format",
    surfaces: ["cli"],
  },

  // ── Shapes ────────────────────────────────────────────────────────
  {
    id: "pptx.add-text-box",
    commandType: "pptx:add-text-box",
    label: "Add text box",
    description: "Insert a new text box on a slide.",
    section: "Insert",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.add-shape",
    commandType: "pptx:add-shape",
    label: "Add shape",
    description: "Insert a new shape (rectangle/ellipse/triangle/etc) on a slide.",
    section: "Insert",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the Insert ▸ Shape menu; CLI exposure is deferred." },
  },
  {
    id: "pptx.delete-shape",
    commandType: "pptx:delete-shape",
    label: "Delete shape",
    description: "Delete a shape from a slide.",
    section: "Edit",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu / delete key." },
  },
  {
    id: "pptx.set-position",
    commandType: "pptx:set-position",
    label: "Set shape position",
    description: "Set a shape's x/y position (in EMU).",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "pptx.set-size",
    commandType: "pptx:set-size",
    label: "Set shape size",
    description: "Set a shape's width/height (in EMU).",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "pptx.set-rotation",
    commandType: "pptx:set-rotation",
    label: "Set shape rotation",
    description: "Rotate a shape by N degrees clockwise around its centre.",
    section: "Edit",
    surfaces: ["cli"],
  },
  {
    id: "pptx.set-shape-fill",
    commandType: "pptx:set-shape-fill",
    label: "Set shape fill",
    description: "Set a shape's fill (solid color, gradient, or none).",
    section: "Format",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the format pane; CLI exposure is deferred." },
  },
  {
    id: "pptx.reorder-shape",
    commandType: "pptx:reorder-shape",
    label: "Reorder shape",
    description: "Send a shape forward / backward / to front / to back.",
    section: "Edit",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu." },
  },
  {
    id: "pptx.duplicate-shape",
    commandType: "pptx:duplicate-shape",
    label: "Duplicate shape",
    description: "Clone a shape on the same slide.",
    section: "Edit",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu / Cmd+D." },
  },
  {
    id: "pptx.group-shapes",
    commandType: "pptx:group-shapes",
    label: "Group shapes",
    description: "Group two or more selected shapes.",
    section: "Edit",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu." },
  },
  {
    id: "pptx.ungroup-shape",
    commandType: "pptx:ungroup-shape",
    label: "Ungroup shape",
    description: "Ungroup a previously grouped shape.",
    section: "Edit",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu." },
  },
  {
    id: "pptx.align-shapes",
    commandType: "pptx:align-shapes",
    label: "Align shapes",
    description: "Align selected shapes (left/center/right/top/middle/bottom).",
    section: "Format",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu; CLI exposure is deferred." },
  },
  {
    id: "pptx.distribute-shapes",
    commandType: "pptx:distribute-shapes",
    label: "Distribute shapes",
    description: "Distribute selected shapes evenly (horizontal / vertical).",
    section: "Format",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the shape context menu; CLI exposure is deferred." },
  },

  // ── Pictures ──────────────────────────────────────────────────────
  {
    id: "pptx.insert-image",
    commandType: "pptx:insert-image",
    label: "Insert image",
    description: "Insert an image on a slide.",
    section: "Insert",
    surfaces: ["cli", "palette"],
    icon: "Image",
  },
  {
    id: "pptx.replace-picture-media",
    commandType: "pptx:replace-picture-media",
    label: "Replace picture media",
    description: "Swap the underlying media for an existing picture (preserves position/size).",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via the picture context menu." },
  },

  // ── Tables ────────────────────────────────────────────────────────
  {
    id: "pptx.insert-table",
    commandType: "pptx:insert-table",
    label: "Insert table",
    description:
      "Insert a native PowerPoint table on a slide from a 2D grid (e.g. a paste from xlsx). Cells stay editable as cells; survives theme/font changes.",
    section: "Insert",
    surfaces: ["cli", "palette"],
    icon: "Table",
    args: [
      { name: "file", flag: "--file <path>", kind: "filepath", required: true, description: "Path to a .pptx file" },
      { name: "slide", flag: "--slide <index>", kind: "number", required: true, description: "0-based slide index" },
      { name: "x", flag: "--x <emu>", kind: "number", required: true, description: "Slide-coord X position in EMU" },
      { name: "y", flag: "--y <emu>", kind: "number", required: true, description: "Slide-coord Y position in EMU" },
      { name: "cx", flag: "--cx <emu>", kind: "number", default: 4572000, description: "Display width in EMU" },
      { name: "cy", flag: "--cy <emu>", kind: "number", description: "Display height in EMU (defaults to ~0.5 inch per row)" },
      { name: "data", flag: "--data <json>", kind: "string", required: true, description: "JSON 2D array of cell values: [[\"A1\", \"B1\"], [1, 2], …]" },
    ],
  },
  {
    id: "pptx.table-set-cell-text",
    commandType: "pptx:table-set-cell-text",
    label: "Set table cell text",
    description: "Replace the text of one table cell.",
    section: "Tables",
    surfaces: ["cli"],
  },
  {
    id: "pptx.table-add-row",
    commandType: "pptx:table-add-row",
    label: "Add table row",
    description: "Insert a row into a table.",
    section: "Tables",
    surfaces: ["cli"],
  },
  {
    id: "pptx.table-delete-row",
    commandType: "pptx:table-delete-row",
    label: "Delete table row",
    description: "Delete a row from a table.",
    section: "Tables",
    surfaces: ["cli"],
  },
  {
    id: "pptx.table-add-column",
    commandType: "pptx:table-add-column",
    label: "Add table column",
    description: "Insert a column into a table.",
    section: "Tables",
    surfaces: ["cli"],
  },
  {
    id: "pptx.table-delete-column",
    commandType: "pptx:table-delete-column",
    label: "Delete table column",
    description: "Delete a column from a table.",
    section: "Tables",
    surfaces: ["cli"],
  },

  // ── Charts ────────────────────────────────────────────────────────
  {
    id: "pptx.insert-chart",
    commandType: "pptx:insert-chart",
    label: "Insert chart",
    description: "Insert a chart on a slide. Embeds a backing .xlsx workbook so 'Edit Data' works in PowerPoint.",
    section: "Insert",
    surfaces: ["cli", "palette"],
    icon: "BarChart3",
    args: [
      { name: "file", flag: "--file <path>", kind: "filepath", required: true, description: "Path to a .pptx file" },
      { name: "slide", flag: "--slide <index>", kind: "number", required: true, description: "0-based slide index" },
      { name: "x", flag: "--x <emu>", kind: "number", required: true, description: "Slide-coord X position in EMU" },
      { name: "y", flag: "--y <emu>", kind: "number", required: true, description: "Slide-coord Y position in EMU" },
      { name: "cx", flag: "--cx <emu>", kind: "number", default: 4572000, description: "Display width in EMU" },
      { name: "cy", flag: "--cy <emu>", kind: "number", default: 3429000, description: "Display height in EMU" },
      { name: "chartType", flag: "--chart-type <type>", kind: "enum", choices: ["bar", "line", "pie", "area"], default: "bar", description: "Chart type" },
      { name: "title", flag: "--title <text>", kind: "string", description: "Chart title" },
      { name: "categories", flag: "--categories <csv>", kind: "string", required: true, description: "Comma-separated category labels (x-axis)" },
      { name: "series", flag: "--series <json>", kind: "string", required: true, description: "JSON array: [{name?, values:number[]}, ...]. Each series.values length must equal --categories length" },
    ],
  },
  {
    id: "pptx.chart-set-title",
    commandType: "pptx:set-chart-title",
    label: "Set chart title",
    description: "Set / replace a chart's title text.",
    section: "Insert",
    surfaces: ["cli"],
  },
  {
    id: "pptx.chart-set-type",
    commandType: "pptx:set-chart-type",
    label: "Set chart type",
    description: "Set the chart's chart type (bar/line/pie/...).",
    section: "Insert",
    surfaces: ["cli"],
  },
  {
    id: "pptx.chart-set-data",
    commandType: "pptx:set-chart-data",
    label: "Set chart data",
    description: "Replace a chart's underlying data series.",
    section: "Insert",
    surfaces: ["cli"],
  },

  // ── Embedded spreadsheets (OLE) ───────────────────────────────────
  {
    id: "pptx.insert-spreadsheet",
    commandType: "pptx:insert-spreadsheet",
    label: "Insert spreadsheet",
    description: "Insert a live OLE-embedded Excel workbook on a slide. Double-clicking the embed in PowerPoint opens the underlying .xlsx in Excel.",
    section: "Insert",
    surfaces: ["cli", "palette"],
    icon: "Table2",
    args: [
      { name: "file", flag: "--file <path>", kind: "filepath", required: true, description: "Path to a .pptx file" },
      { name: "slide", flag: "--slide <index>", kind: "number", required: true, description: "0-based slide index" },
      { name: "x", flag: "--x <emu>", kind: "number", required: true, description: "Slide-coord X position in EMU" },
      { name: "y", flag: "--y <emu>", kind: "number", required: true, description: "Slide-coord Y position in EMU" },
      { name: "cx", flag: "--cx <emu>", kind: "number", default: 2743200, description: "Display width in EMU" },
      { name: "cy", flag: "--cy <emu>", kind: "number", default: 1828800, description: "Display height in EMU" },
      { name: "data", flag: "--data <json>", kind: "string", required: true, description: "JSON 2D array of cell values: [[\"A1\", \"B1\"], [1, 2], …]" },
      { name: "sheetName", flag: "--sheet-name <name>", kind: "string", default: "Sheet1", description: "Worksheet name" },
    ],
  },
  // ── "Insert from xlsx" palette wrappers ──────────────────────────
  // These three actions don't dispatch a bus command directly; they
  // open the XlsxRangePickerDialog with a preselected mode and the
  // dialog's submit handler routes through the shared
  // `applyXlsxEmbed` dispatcher to the right `pptx:insert-*`
  // command. Catalogued here purely so they appear in Cmd+K with
  // proper i18n + icons; CLI users keep using the lower-level
  // `pptx:insert-spreadsheet` / `pptx:insert-chart` /
  // `pptx:insert-table` commands directly.
  {
    id: "pptx.insert-table-from-xlsx",
    commandType: null,
    label: "Insert table from xlsx",
    description: "Pick a range from an .xlsx file and insert it as a native PowerPoint table.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "Table",
  },
  {
    id: "pptx.insert-spreadsheet-from-xlsx",
    commandType: null,
    label: "Insert spreadsheet (live)",
    description: "Pick a range from an .xlsx file and embed the workbook as a live OLE object on the slide.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "Table2",
  },
  {
    id: "pptx.insert-chart-from-xlsx",
    commandType: null,
    label: "Insert chart from xlsx",
    description: "Pick a range from an .xlsx file and project it into a chart on the slide (first row = series, first column = categories).",
    section: "Insert",
    surfaces: ["palette"],
    icon: "BarChart3",
  },
  {
    id: "pptx.update-spreadsheet",
    commandType: "pptx:update-spreadsheet",
    label: "Update embedded spreadsheet",
    description: "Replace the bytes of a previously embedded OLE spreadsheet (used by the editor's double-click → edit → save flow).",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Driven by the embedded-spreadsheet edit-in-place flow." },
  },

  // ── Animations ────────────────────────────────────────────────────
  {
    id: "pptx.add-shape-animation",
    commandType: "pptx:add-shape-animation",
    label: "Add shape animation",
    description: "Attach an entry/emphasis/exit/motion-path animation to a shape.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.set-shape-animation",
    commandType: "pptx:set-shape-animation",
    label: "Edit shape animation",
    description: "Patch trigger / direction / duration / delay on an existing shape animation.",
    section: "Slide",
    surfaces: ["cli"],
  },
  {
    id: "pptx.remove-shape-animation",
    commandType: "pptx:remove-shape-animation",
    label: "Remove shape animation",
    description: "Remove a shape animation from a slide.",
    section: "Slide",
    surfaces: ["cli", "palette"],
  },
  {
    id: "pptx.reorder-shape-animations",
    commandType: "pptx:reorder-shape-animations",
    label: "Reorder shape animations",
    description: "Reorder the animation sequence on a slide.",
    section: "Slide",
    surfaces: ["cli"],
  },

  // ── Connectors ────────────────────────────────────────────────────
  {
    id: "pptx.add-connector",
    commandType: "pptx:add-connector",
    label: "Add connector",
    description: "Add a straight/elbow/curved connector between two shapes.",
    section: "Insert",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the Insert ▸ Connector menu; CLI exposure is deferred." },
  },
  {
    id: "pptx.set-connector-endpoint",
    commandType: "pptx:set-connector-endpoint",
    label: "Set connector endpoint",
    description: "Reattach a connector endpoint to a different shape / port.",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via the connector drag handles." },
  },
  {
    id: "pptx.set-connector-style",
    commandType: "pptx:set-connector-style",
    label: "Set connector style",
    description: "Set a connector's stroke style / arrowheads.",
    section: "Format",
    surfaces: [],
    hidden: { reason: "Reached via the format pane." },
  },
  {
    id: "pptx.set-connector-waypoint",
    commandType: "pptx:set-connector-waypoint",
    label: "Set connector waypoint",
    description: "Set / move an elbow connector's bend point.",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via the connector drag handles." },
  },
  {
    id: "pptx.reroute-connector",
    commandType: "pptx:reroute-connector",
    label: "Reroute connector",
    description: "Recompute an elbow connector's waypoints.",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via the connector context menu." },
  },
  {
    id: "pptx.swap-connector-direction",
    commandType: "pptx:swap-connector-direction",
    label: "Swap connector direction",
    description: "Swap a connector's start/end shapes.",
    section: "Edit",
    surfaces: [],
    hidden: { reason: "Reached via the connector context menu." },
  },

  // ── Comments ──────────────────────────────────────────────────────
  {
    id: "pptx.add-comment",
    commandType: "pptx:add-comment",
    label: "Add comment",
    description: "Anchor a comment to a slide.",
    section: "Comments",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the comment toolbar; CLI exposure is deferred." },
  },
  {
    id: "pptx.reply-comment",
    commandType: "pptx:reply-comment",
    label: "Reply to comment",
    description: "Append a reply to an existing comment thread.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },
  {
    id: "pptx.resolve-comment",
    commandType: "pptx:resolve-comment",
    label: "Resolve comment",
    description: "Mark a comment thread as resolved.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },
  {
    id: "pptx.edit-comment",
    commandType: "pptx:edit-comment",
    label: "Edit comment",
    description: "Edit a comment's text.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },
  {
    id: "pptx.delete-comment",
    commandType: "pptx:delete-comment",
    label: "Delete comment",
    description: "Delete a comment thread.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },

  // ── Palette-only convenience entries (UI sugar over add-shape /
  //    add-connector / view actions) ────────────────────────────────
  {
    id: "pptx.add-rect",
    commandType: null,
    label: "Insert rectangle",
    description: "Insert a rectangle shape on the active slide.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "pptx.add-ellipse",
    commandType: null,
    label: "Insert ellipse",
    description: "Insert an ellipse shape on the active slide.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "pptx.add-arrow",
    commandType: null,
    label: "Insert arrow",
    description: "Insert a right-arrow shape on the active slide.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "pptx.add-connector-elbow",
    commandType: null,
    label: "Draw elbow connector",
    description: "Activate the elbow-connector tool.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "pptx.add-connector-straight",
    commandType: null,
    label: "Draw straight connector",
    description: "Activate the straight-connector tool.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "pptx.add-connector-curved",
    commandType: null,
    label: "Draw curved connector",
    description: "Activate the curved-connector tool.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "pptx.zoom-reset",
    commandType: null,
    label: "Reset zoom to 100%",
    description: "Restore the canvas zoom level to 100%.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pptx.present-from-start",
    commandType: null,
    label: "Start presentation from beginning",
    description: "Enter presentation mode at slide 1.",
    section: "View",
    surfaces: ["palette"],
    shortcut: "F5",
  },
  {
    id: "pptx.present-from-current",
    commandType: null,
    label: "Start presentation from current slide",
    description: "Enter presentation mode at the active slide.",
    section: "View",
    surfaces: ["palette"],
    shortcut: "Shift+F5",
  },
];
