export * from "./payloads.js";
export { allDocxHandlers, docxHandlersById } from "./registry.js";
export { insertTextHandler } from "./insert-text.js";
export { deleteRangeHandler } from "./delete-range.js";
export { formatRangeHandler } from "./format-range.js";
export { insertParagraphHandler } from "./insert-paragraph.js";
export { setParagraphStyleHandler } from "./set-paragraph-style.js";
export { addCommentHandler } from "./add-comment.js";
export { paragraphPlainText } from "./helpers.js";
export { resolveCommentHandler } from "./resolve-comment.js";
export { replyCommentHandler } from "./reply-comment.js";
export { deleteCommentHandler } from "./delete-comment.js";
export { setHeaderTextHandler } from "./set-header-text.js";
export { setFooterTextHandler } from "./set-footer-text.js";
export { acceptChangeHandler } from "./accept-change.js";
export { rejectChangeHandler } from "./reject-change.js";
export { insertTableHandler } from "./insert-table.js";
export { setCellContentHandler } from "./set-cell-content.js";
export { insertRowHandler } from "./insert-row.js";
export { insertColumnHandler } from "./insert-column.js";
