export { runCli } from "./cli.js";
export {
  parseSelector,
  type Selector,
  type ParagraphSelector,
  type ParagraphRangeSelector,
} from "./selector.js";
export {
  DATA_DIR_SCHEMA_VERSION,
  DOCUMENT_RECORD_SCHEMA_VERSION,
  createLocalSessionStore,
  createLocalFilesystemSessionStorageAdapter,
  createObjectSessionStorageAdapter,
  LocalFilesystemSessionStorageAdapter,
  ObjectSessionStorageAdapter,
  resolveOfficeAiDataDir,
  SESSION_RECORD_SCHEMA_VERSION,
  SessionStoreCorruptError,
  SessionStoreStorageError,
  type LocalSessionStoreOptions,
  type ObjectSessionStorageAdapterOptions,
  type ObjectSessionStorageBackend,
  type SessionDuplicateResult,
  type SessionStoreCleanupResult,
  type SessionStoreInspection,
  type SessionStoreMigrationRecord,
  type SessionStoreMigrationResult,
  type SessionStorageAdapter,
  type SessionStorageCapabilities,
  type SessionStorageOperation,
  type SessionStorageRemoveOptions,
  type StoredCommandExportRef,
  type StoredCommandLogEntry,
  type StoredCommandProvenance,
  type StoredDiagnostic,
  type StoredDocumentRecord,
  type StoredExportRecord,
  type StoredOfficeFormat,
  type StoredPendingChange,
  type StoredSessionRecord,
} from "./session-store.js";
export {
  projectOfficeDocument,
  projectionDocumentEnvelope,
  type ProjectionDocumentMeta,
  type ProjectionFormat,
  type ProjectionKind,
  type ProjectionOptions,
  type ProjectionSource,
} from "./projections.js";
