/**
 * Action catalogue for DOCX. The single source of truth tying
 * together the bus command type, agent/CLI callability, and web
 * surfaces for every public action.
 *
 * Seeded from the existing `office-agent docx …` subcommands in
 * `packages/agent/src/cli.ts` and the palette wiring in
 * `apps/web/app/editor/DocxEditor.tsx`. Each entry is a mechanical
 * translation — no behavioural change vs the hand-rolled wiring it
 * replaces.
 *
 * Add new public actions HERE first; the parity check
 * (`scripts/check-action-parity.mjs`) refuses to land a registered
 * command-bus handler that has no catalogue entry.
 */

import type { ActionDescriptor } from "@officeai/core";

/**
 * Page-size presets in twips (1440 twips = 1 inch). Used by
 * `docx.set-page-size` to translate `--preset letter|legal|a4|a3|a5`
 * into typed `{ w, h }` payload fields.
 */
const PAGE_SIZE_PRESETS = {
  letter: { w: 12240, h: 15840 },
  legal: { w: 12240, h: 20160 },
  a4: { w: 11906, h: 16838 },
  a3: { w: 16838, h: 23811 },
  a5: { w: 8391, h: 11906 },
} as const;

/**
 * Shared payload builder for `docx:set-page-setup` catalogue entries.
 * Splits the flat parsed CLI/MCP args into `pgSz` (page geometry) and
 * `pgMar` (margins) sub-payloads, omitting either when no relevant
 * fields were supplied.
 */
function buildSetPageSetupPayload(parsed: Record<string, unknown>): {
  paragraphIndex: number;
  pgSz?: { w?: number; h?: number; orient?: "portrait" | "landscape" };
  pgMar?: {
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
    header?: number;
    footer?: number;
    gutter?: number;
  };
} {
  const paragraphIndex = Number(parsed.paragraphIndex);
  const pgSz: { w?: number; h?: number; orient?: "portrait" | "landscape" } = {};
  if (parsed.width !== undefined) pgSz.w = Number(parsed.width);
  if (parsed.height !== undefined) pgSz.h = Number(parsed.height);
  if (parsed.orient !== undefined) pgSz.orient = String(parsed.orient) as "portrait" | "landscape";

  const pgMar: {
    top?: number;
    right?: number;
    bottom?: number;
    left?: number;
    header?: number;
    footer?: number;
    gutter?: number;
  } = {};
  for (const f of ["top", "right", "bottom", "left", "header", "footer", "gutter"] as const) {
    if (parsed[f] !== undefined) pgMar[f] = Number(parsed[f]);
  }

  const out: ReturnType<typeof buildSetPageSetupPayload> = { paragraphIndex };
  if (Object.keys(pgSz).length > 0) out.pgSz = pgSz;
  if (Object.keys(pgMar).length > 0) out.pgMar = pgMar;
  return out;
}

/**
 * Free-form section taxonomy for DOCX. Kept stable so palette /
 * help-screen grouping doesn't churn between releases.
 */
export type DocxActionSection =
  | "File"
  | "Read"
  | "Edit"
  | "Insert"
  | "Format"
  | "Layout"
  | "Tables"
  | "Lists"
  | "Hyperlinks"
  | "Headers"
  | "Comments"
  | "Review"
  | "View"
  | "Mode"
  | "Collaboration";

export const docxActions: ReadonlyArray<ActionDescriptor> = [
  // ── File ──────────────────────────────────────────────────────────
  {
    id: "docx.create",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Create blank document",
    description: "Create a brand-new blank .docx file at --out (one empty paragraph, no styles part).",
    section: "File",
    surfaces: [],
    args: [
      {
        name: "out",
        flag: "--out <path>",
        kind: "filepath",
        required: true,
        description: "Path to write the new .docx file",
      },
    ],
  },
  {
    id: "docx.inspect",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Inspect document",
    description: "Print a structural summary (paragraphs, tables, comments, parts) as JSON.",
    section: "Read",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "withRuns",
        flag: "--with-runs",
        kind: "boolean",
        description:
          "Include per-paragraph run breakdown (offset, length, text) so callers can target precise text ranges",
      },
    ],
  },
  {
    id: "docx.read",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Read document",
    description: "Read a DOCX file as Markdown, structured JSON, or plain text.",
    section: "Read",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "format",
        flag: "--format <fmt>",
        kind: "enum",
        choices: ["markdown", "json", "text"],
        default: "markdown",
        description: "Output format",
      },
      {
        name: "range",
        flag: "--range <selector>",
        kind: "selector",
        description: "Selector e.g. paragraph:0..paragraph:5",
      },
      {
        name: "withTables",
        flag: "--with-tables",
        kind: "boolean",
        description:
          "JSON: include a top-level `tables` array with table id, dimensions, and per-cell paragraph ids/text",
      },
    ],
  },
  {
    id: "docx.search",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Search document",
    description: "Search a DOCX file for text and print matches as JSON.",
    section: "Read",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "query",
        flag: "-q, --query <text>",
        kind: "string",
        required: true,
        description: "Search query",
      },
      {
        name: "caseSensitive",
        flag: "--case-sensitive",
        kind: "boolean",
        description: "Case-sensitive search",
      },
      {
        name: "regex",
        flag: "--regex",
        kind: "boolean",
        description: "Treat the query as a regular expression",
      },
    ],
  },
  {
    id: "docx.diff",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Diff documents",
    description: "Compute a structural diff between two DOCX files.",
    section: "Read",
    surfaces: [],
    args: [
      {
        name: "before",
        flag: "--before <path>",
        kind: "filepath",
        required: true,
        description: "Path to the baseline .docx file",
      },
      {
        name: "after",
        flag: "--after <path>",
        kind: "filepath",
        required: true,
        description: "Path to the modified .docx file",
      },
    ],
  },

  // ── Text mutations ────────────────────────────────────────────────
  {
    id: "docx.insert-text",
    commandType: "docx:insert-text",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert text",
    description: "Insert text at a position selector and write the result.",
    section: "Edit",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector e.g. section:0/paragraph:0/run:0/text:5",
      },
      { name: "text", flag: "--text <text>", kind: "string", required: true, description: "Text to insert" },
    ],
  },
  {
    id: "docx.delete-range",
    commandType: "docx:delete-range",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete range",
    description:
      "Delete a range of text. Range may span runs/paragraphs (e.g. paragraph:0/text:0..20 or paragraph:0..2).",
    section: "Edit",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "range",
        flag: "--range <selector>",
        kind: "selector",
        required: true,
        description: "Range selector e.g. paragraph:0/text:0..5 or paragraph:0..2",
      },
    ],
  },
  {
    id: "docx.replace-text",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Replace paragraph text",
    description:
      "Replace the entire text content of a paragraph (delete-range + insert-text in one mutation batch).",
    section: "Edit",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "paragraph",
        flag: "--paragraph <n>",
        kind: "number",
        required: true,
        description: "0-based paragraph index",
      },
      {
        name: "text",
        flag: "--text <text>",
        kind: "string",
        required: true,
        description: "New text content for the paragraph (may be empty)",
      },
    ],
  },
  {
    id: "docx.format-range",
    commandType: "docx:format-range",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Format text range",
    description:
      "Apply text formatting to a range (bold/italic/underline/strikethrough/font/size/color/highlight).",
    section: "Format",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "range",
        flag: "--range <selector>",
        kind: "selector",
        required: true,
        description: "Range selector e.g. paragraph:0/text:0..5 or paragraph:0..2",
      },
      {
        name: "bold",
        flag: "--bold <bool>",
        kind: "string",
        description: "true|false to set, omit to leave unchanged",
      },
      { name: "italic", flag: "--italic <bool>", kind: "string", description: "true|false" },
      { name: "underline", flag: "--underline <bool>", kind: "string", description: "true|false" },
      { name: "strike", flag: "--strike <bool>", kind: "string", description: "true|false" },
      { name: "fontFamily", flag: "--font-family <name>", kind: "string", description: "Run font family" },
      {
        name: "fontSize",
        flag: "--font-size <halfPoints>",
        kind: "number",
        description: "Run font size in half-points (e.g. 24 = 12pt)",
      },
      { name: "color", flag: "--color <RRGGBB>", kind: "string", description: "Hex color without leading #" },
      {
        name: "highlight",
        flag: "--highlight <name>",
        kind: "string",
        description: "Highlight color name (yellow|green|cyan|red|...)",
      },
    ],
  },
  {
    id: "docx.style",
    commandType: "docx:set-paragraph-style",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set paragraph style",
    description: "Set the paragraph style at a position selector and write the result.",
    section: "Format",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector targeting a paragraph",
      },
      {
        name: "style",
        flag: "--style <styleId>",
        kind: "string",
        required: true,
        description: "Style id, e.g. Heading1",
      },
    ],
  },
  {
    id: "docx.insert-paragraph",
    commandType: "docx:insert-paragraph",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert paragraph",
    description:
      "Insert a new paragraph at the given position selector. Optional --style applies a paragraph style id.",
    section: "Edit",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector targeting a paragraph (e.g. paragraph:0)",
      },
      {
        name: "style",
        flag: "--style <styleId>",
        kind: "string",
        description: "Paragraph style id to apply (e.g. Heading1, Heading2, ListParagraph)",
      },
    ],
  },

  // ── Comments ──────────────────────────────────────────────────────
  {
    id: "docx.add-comment",
    commandType: "docx:add-comment",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Add comment",
    description: "Add a comment to a range selector and write the result.",
    section: "Comments",
    surfaces: ["palette", "toolbar"],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "range",
        flag: "--range <selector>",
        kind: "selector",
        required: true,
        description: "Range selector e.g. paragraph:0/text:0..5",
      },
      { name: "text", flag: "--text <text>", kind: "string", required: true, description: "Comment text" },
      {
        name: "author",
        flag: "--author <name>",
        kind: "string",
        default: "office-agent",
        description: "Comment author",
      },
      {
        name: "initials",
        flag: "--initials <initials>",
        kind: "string",
        default: "OA",
        description: "Comment author initials",
      },
    ],
  },
  {
    id: "docx.resolve-comment",
    commandType: "docx:resolve-comment",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Resolve comment",
    description: "Mark a comment as resolved (or re-open with --reopen) and write the result.",
    section: "Comments",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "CheckCheck",
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "id",
        flag: "--id <commentId>",
        kind: "string",
        required: true,
        description: "Target comment id (as exposed by `docx inspect`)",
      },
      {
        name: "reopen",
        flag: "--reopen",
        kind: "boolean",
        description: "Re-open a previously resolved comment instead of resolving it",
      },
    ],
  },
  {
    id: "docx.reply-comment",
    commandType: "docx:reply-comment",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Reply to comment",
    description: "Append a reply to an existing comment and write the result.",
    section: "Comments",
    surfaces: ["palette", "contextMenu"],
    icon: "Reply",
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "parent",
        flag: "--parent <commentId>",
        kind: "string",
        required: true,
        description: "Parent comment id",
      },
      { name: "text", flag: "--text <text>", kind: "string", required: true, description: "Reply text" },
      {
        name: "author",
        flag: "--author <name>",
        kind: "string",
        default: "office-agent",
        description: "Reply author",
      },
      {
        name: "initials",
        flag: "--initials <initials>",
        kind: "string",
        description: "Reply author initials",
      },
    ],
  },
  {
    id: "docx.delete-comment",
    commandType: "docx:delete-comment",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete comment",
    description: "Delete a comment (and its reply thread) and write the result.",
    section: "Comments",
    surfaces: ["palette", "contextMenu"],
    icon: "Trash2",
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "id",
        flag: "--id <commentId>",
        kind: "string",
        required: true,
        description: "Target comment id",
      },
    ],
  },

  // ── Tracked changes ───────────────────────────────────────────────
  {
    id: "docx.accept-change",
    commandType: "docx:accept-change",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Accept tracked change",
    description: "Accept a tracked change (insertion folds in, deletion lands).",
    section: "Review",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "id",
        flag: "--id <revisionId>",
        kind: "string",
        required: true,
        description: "Tracked-change revision id (the w:id on <w:ins>/<w:del>)",
      },
    ],
  },
  {
    id: "docx.reject-change",
    commandType: "docx:reject-change",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Reject tracked change",
    description: "Reject a tracked change (insertion is dropped, deletion is undone).",
    section: "Review",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "id",
        flag: "--id <revisionId>",
        kind: "string",
        required: true,
        description: "Tracked-change revision id",
      },
    ],
  },

  // ── Insert ────────────────────────────────────────────────────────
  {
    id: "docx.insert-image",
    commandType: "docx:insert-image",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert image",
    description: "Insert an inline image at a position selector. Reads image bytes from --image.",
    section: "Insert",
    surfaces: ["toolbar", "palette"],
    icon: "Image",
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector targeting a paragraph",
      },
      {
        name: "image",
        flag: "--image <path>",
        kind: "filepath",
        required: true,
        description: "Path to image file (PNG/JPEG/GIF/BMP/TIFF/WebP/SVG)",
      },
      {
        name: "width",
        flag: "--width <px>",
        kind: "number",
        default: 200,
        description: "Display width in pixels @ 96 DPI (default: 200)",
      },
      {
        name: "height",
        flag: "--height <px>",
        kind: "number",
        default: 200,
        description: "Display height in pixels @ 96 DPI (default: 200)",
      },
      {
        name: "mime",
        flag: "--mime <type>",
        kind: "string",
        description: "Override mime type (auto-detected from extension by default)",
      },
      {
        name: "alt",
        flag: "--alt <text>",
        kind: "string",
        description: "Alt text (populates wp:docPr@descr)",
      },
      { name: "name", flag: "--name <name>", kind: "string", description: "Display name (wp:docPr@name)" },
    ],
  },
  {
    id: "docx.insert-table",
    commandType: "docx:insert-table",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert table",
    description: "Insert an empty rows × cols table at a position selector.",
    section: "Tables",
    surfaces: ["palette"],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector targeting a paragraph",
      },
      { name: "rows", flag: "--rows <n>", kind: "number", required: true, description: "Row count" },
      { name: "cols", flag: "--cols <n>", kind: "number", required: true, description: "Column count" },
      {
        name: "colWidths",
        flag: "--col-widths <csv>",
        kind: "string",
        description: "Optional comma-separated column widths in twips",
      },
    ],
  },
  {
    id: "docx.insert-row",
    commandType: "docx:insert-row",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert table row",
    description: "Insert a row into a table.",
    section: "Tables",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id (use `docx inspect` to find ids)",
      },
      {
        name: "at",
        flag: "--at <n>",
        kind: "number",
        required: true,
        description: "0-based row index; equal to row count to append",
      },
    ],
  },
  {
    id: "docx.insert-column",
    commandType: "docx:insert-column",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert table column",
    description: "Insert a column into a table.",
    section: "Tables",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id",
      },
      { name: "at", flag: "--at <n>", kind: "number", required: true, description: "0-based column index" },
      {
        name: "width",
        flag: "--width <twips>",
        kind: "number",
        description: "Column width in twips (defaults to equal split)",
      },
    ],
  },
  {
    id: "docx.delete-row",
    commandType: "docx:delete-row",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Delete table row",
    description: "Remove a row from a table. The table must have at least 2 rows.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "Minus",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id (see `docx inspect`)",
      },
      { name: "at", flag: "--at <n>", kind: "number", required: true, description: "0-based row index" },
    ],
    buildPayload: ({ tableId, at }) => ({ tableId: String(tableId), at: Number(at) }),
  },
  {
    id: "docx.delete-column",
    commandType: "docx:delete-column",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Delete table column",
    description: "Remove a column from a table. The table must have at least 2 columns.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "Minus",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id",
      },
      { name: "at", flag: "--at <n>", kind: "number", required: true, description: "0-based column index" },
    ],
    buildPayload: ({ tableId, at }) => ({ tableId: String(tableId), at: Number(at) }),
  },
  {
    id: "docx.delete-table",
    commandType: "docx:delete-table",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Delete table",
    description: "Remove a top-level table from the document.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "Trash2",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id",
      },
    ],
    buildPayload: ({ tableId }) => ({ tableId: String(tableId) }),
  },
  {
    id: "docx.set-cell-text",
    commandType: "docx:set-cell-content",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set table cell text",
    description:
      "Replace one table cell's content with a single plain-text paragraph. Discover --table-id values via `docx read --format json --with-tables`.",
    section: "Tables",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id (see `docx read --format json --with-tables`)",
      },
      { name: "row", flag: "--row <n>", kind: "number", required: true, description: "0-based row index" },
      { name: "col", flag: "--col <n>", kind: "number", required: true, description: "0-based column index" },
      {
        name: "text",
        flag: "--text <text>",
        kind: "string",
        required: true,
        description: "Text to place in the cell",
      },
    ],
  },

  // ── Charts ────────────────────────────────────────────────────────
  {
    id: "docx.insert-chart",
    commandType: "docx:insert-chart",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert chart",
    description:
      "Insert an inline chart at a position selector. Embeds a backing .xlsx workbook so 'Edit Data' works in Word.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "BarChart3",
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector targeting a paragraph",
      },
      {
        name: "chartType",
        flag: "--chart-type <type>",
        kind: "enum",
        choices: ["bar", "line", "pie", "area"],
        default: "bar",
        description: "Chart type",
      },
      { name: "title", flag: "--title <text>", kind: "string", description: "Chart title" },
      {
        name: "categories",
        flag: "--categories <csv>",
        kind: "string",
        required: true,
        description: "Comma-separated category labels (x-axis)",
      },
      {
        name: "series",
        flag: "--series <json>",
        kind: "string",
        required: true,
        description:
          "JSON array: [{name?, values:number[]}, ...]. Each series.values length must equal --categories length",
      },
      {
        name: "width",
        flag: "--width <px>",
        kind: "number",
        default: 480,
        description: "Display width in pixels @ 96 DPI",
      },
      {
        name: "height",
        flag: "--height <px>",
        kind: "number",
        default: 320,
        description: "Display height in pixels @ 96 DPI",
      },
    ],
  },
  {
    id: "docx.set-chart-data",
    commandType: "docx:set-chart-data",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set chart data",
    description: "Replace categories + series for an existing chart and refresh the embedded workbook.",
    section: "Insert",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "chartPartPath",
        flag: "--chart-part-path <path>",
        kind: "string",
        required: true,
        description: "Chart part path, e.g. word/charts/chart1.xml",
      },
      {
        name: "categories",
        flag: "--categories <csv>",
        kind: "string",
        required: true,
        description: "Comma-separated category labels",
      },
      {
        name: "series",
        flag: "--series <json>",
        kind: "string",
        required: true,
        description: "JSON array: [{name?, values:number[]}, ...]",
      },
    ],
  },
  {
    id: "docx.set-chart-title",
    commandType: "docx:set-chart-title",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set chart title",
    description: "Set / clear the title of an existing chart.",
    section: "Insert",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "chartPartPath",
        flag: "--chart-part-path <path>",
        kind: "string",
        required: true,
        description: "Chart part path",
      },
      {
        name: "title",
        flag: "--title <text>",
        kind: "string",
        description: "New title text; omit (or pass --clear) to remove",
      },
      { name: "clear", flag: "--clear", kind: "boolean", description: "Clear the existing title" },
    ],
  },
  {
    id: "docx.insert-footnote",
    commandType: "docx:insert-footnote",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert footnote",
    description: "Insert a footnote reference at the caret and add an empty footnote body.",
    section: "Insert",
    surfaces: ["palette", "toolbar"],
  },
  {
    id: "docx.set-footnote-body",
    commandType: "docx:set-footnote-body",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set footnote body",
    description: "Replace the body of an existing footnote with new block content.",
    section: "Insert",
    surfaces: ["palette"],
    hidden: {
      reason: "Footnote model + commands shipped in F1; UI surfaces land in a follow-up phase.",
    },
  },
  {
    id: "docx.delete-footnote",
    commandType: "docx:delete-footnote",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete footnote",
    description: "Remove a footnote and strip every reference leaf to it across body + headers/footers.",
    section: "Insert",
    surfaces: ["palette"],
    hidden: {
      reason: "Footnote model + commands shipped in F1; UI surfaces land in a follow-up phase.",
    },
  },
  {
    id: "docx.set-chart-type",
    commandType: "docx:set-chart-type",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set chart type",
    description: "Switch the active plot type of an existing chart (bar/line/pie/area).",
    section: "Insert",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "chartPartPath",
        flag: "--chart-part-path <path>",
        kind: "string",
        required: true,
        description: "Chart part path",
      },
      {
        name: "chartType",
        flag: "--chart-type <type>",
        kind: "enum",
        choices: ["bar", "line", "pie", "area"],
        required: true,
        description: "Chart type",
      },
    ],
  },
  {
    id: "docx.insert-spreadsheet",
    commandType: "docx:insert-spreadsheet",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert spreadsheet",
    description:
      "Insert a live OLE-embedded Excel workbook at a position selector. Double-clicking the embed in Word opens the underlying .xlsx in Excel.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "Table2",
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "at",
        flag: "--at <selector>",
        kind: "selector",
        required: true,
        description: "Position selector targeting a paragraph",
      },
      {
        name: "data",
        flag: "--data <json>",
        kind: "string",
        required: true,
        description: 'JSON 2D array of cell values: [["A1", "B1"], [1, 2], …]',
      },
      {
        name: "sheetName",
        flag: "--sheet-name <name>",
        kind: "string",
        default: "Sheet1",
        description: "Worksheet name",
      },
    ],
  },
  // ── "Insert from xlsx" palette wrappers ──────────────────────────
  // These three actions don't dispatch a bus command directly; they
  // open the XlsxRangePickerDialog with a preselected mode and the
  // dialog's submit handler dispatches the right `docx:insert-*`
  // command via the shared `applyXlsxEmbed` dispatcher. Catalogued
  // here purely so they appear in Cmd+K with proper i18n + icons;
  // CLI users keep using the lower-level `docx:insert-spreadsheet`
  // / `docx:insert-chart` / `docx:insert-table` commands directly.
  {
    id: "docx.insert-table-from-xlsx",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert table from xlsx",
    description: "Pick a range from an .xlsx file and insert it as a native Word table.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "Table",
  },
  {
    id: "docx.insert-spreadsheet-from-xlsx",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert spreadsheet (live)",
    description: "Pick a range from an .xlsx file and embed the workbook as a live OLE object.",
    section: "Insert",
    surfaces: ["palette"],
    icon: "Table2",
  },
  {
    id: "docx.insert-chart-from-xlsx",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert chart from xlsx",
    description:
      "Pick a range from an .xlsx file and project it into a chart (first row = series, first column = categories).",
    section: "Insert",
    surfaces: ["palette"],
    icon: "BarChart3",
  },
  {
    id: "docx.update-spreadsheet",
    commandType: "docx:update-spreadsheet",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Update spreadsheet",
    description:
      "Replace the bytes of an existing OLE-embedded Excel workbook (used by the editor's double-click → edit → save loop).",
    section: "Insert",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "embeddingPartPath",
        flag: "--embedding-part-path <path>",
        kind: "string",
        required: true,
        description: "Part path of the embedded workbook, e.g. word/embeddings/oleObject1.xlsx",
      },
      {
        name: "xlsx",
        flag: "--xlsx <path>",
        kind: "filepath",
        required: true,
        description: "Path to the new .xlsx file whose bytes will replace the embed",
      },
    ],
  },

  // ── Hyperlinks ────────────────────────────────────────────────────
  {
    id: "docx.insert-hyperlink",
    commandType: "docx:insert-hyperlink",
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert hyperlink",
    description: "Wrap a flat-text range in a paragraph with a hyperlink.",
    section: "Hyperlinks",
    surfaces: ["palette"],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target paragraph id (use `docx read --format json` to find ids)",
      },
      {
        name: "start",
        flag: "--start <n>",
        kind: "number",
        required: true,
        description: "Inclusive start offset",
      },
      { name: "end", flag: "--end <n>", kind: "number", required: true, description: "Exclusive end offset" },
      {
        name: "target",
        flag: "--target <url>",
        kind: "string",
        description: "External URL target (mutually exclusive with --anchor)",
      },
      {
        name: "anchor",
        flag: "--anchor <name>",
        kind: "string",
        description: "Internal bookmark anchor (mutually exclusive with --target)",
      },
      { name: "tooltip", flag: "--tooltip <text>", kind: "string", description: "Tooltip text" },
    ],
  },
  {
    id: "docx.remove-hyperlink",
    commandType: "docx:remove-hyperlink",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Remove hyperlink",
    description: "Unwrap a hyperlink from a paragraph (optionally reaping its relationship).",
    section: "Hyperlinks",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target paragraph id",
      },
      {
        name: "hyperlinkId",
        flag: "--hyperlink-id <id>",
        kind: "string",
        required: true,
        description: "Hyperlink node id",
      },
    ],
  },

  // ── Lists ─────────────────────────────────────────────────────────
  {
    id: "docx.set-list",
    commandType: "docx:set-paragraph-list",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set paragraph list",
    description: "Set or replace numbering (list) on a paragraph.",
    section: "Lists",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target paragraph id",
      },
      {
        name: "numId",
        flag: "--num-id <n>",
        kind: "number",
        required: true,
        description: "Numbering instance id (matches w:num/@w:numId)",
      },
      {
        name: "ilvl",
        flag: "--ilvl <n>",
        kind: "number",
        default: 0,
        description: "0-based level within the abstract numbering definition",
      },
    ],
  },
  {
    id: "docx.remove-list",
    commandType: "docx:remove-paragraph-list",
    format: "docx",
    agentCallable: true,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Remove paragraph list",
    description: "Remove numbering (list) from a paragraph.",
    section: "Lists",
    surfaces: [],
    args: [
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target paragraph id",
      },
    ],
    buildPayload: (parsed) => ({ paragraphId: parsed.paragraphId as string }),
  },

  // ── Layout ────────────────────────────────────────────────────────
  {
    id: "docx.align",
    commandType: "docx:set-paragraph-alignment",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set paragraph alignment",
    description: "Set (or clear with --clear) a paragraph's <w:jc> alignment.",
    section: "Layout",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target paragraph id",
      },
      {
        name: "alignment",
        flag: "--alignment <value>",
        kind: "string",
        description: "left | center | right | justify",
      },
      { name: "clear", flag: "--clear", kind: "boolean", description: "Clear any existing alignment" },
    ],
  },
  {
    id: "docx.indent",
    commandType: "docx:set-paragraph-indent",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set paragraph indent",
    description: "Step a paragraph's left indent by --delta twips (negative outdents).",
    section: "Layout",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target paragraph id",
      },
      {
        name: "delta",
        flag: "--delta <twips>",
        kind: "number",
        required: true,
        description: "Signed delta in twips applied to indentation.left",
      },
    ],
  },

  // ── Headers / Footers ─────────────────────────────────────────────
  {
    id: "docx.header",
    commandType: "docx:set-header-text",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set header text",
    description: "Replace one header paragraph's text content.",
    section: "Headers",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "part",
        flag: "--part <path>",
        kind: "string",
        required: true,
        description: "Header part path, e.g. word/header1.xml",
      },
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based paragraph index inside the header",
      },
      {
        name: "text",
        flag: "--text <text>",
        kind: "string",
        required: true,
        description: "New plain-text content",
      },
    ],
  },
  {
    id: "docx.footer",
    commandType: "docx:set-footer-text",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set footer text",
    description: "Replace one footer paragraph's text content.",
    section: "Headers",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "part",
        flag: "--part <path>",
        kind: "string",
        required: true,
        description: "Footer part path, e.g. word/footer1.xml",
      },
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based paragraph index inside the footer",
      },
      {
        name: "text",
        flag: "--text <text>",
        kind: "string",
        required: true,
        description: "New plain-text content",
      },
    ],
  },

  {
    id: "docx.set-header-footer-blocks",
    commandType: "docx:set-header-footer-blocks",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set header/footer body",
    description:
      "Replace the entire body of a header or footer part with a typed BlockNode array (preserves multi-paragraph + page-number-field + image leaves).",
    section: "Headers",
    surfaces: [],
  },
  {
    id: "docx.insert-header-footer-image",
    commandType: "docx:insert-header-footer-image",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert image into header/footer",
    description:
      "Insert an inline image into a header or footer part. The relationship lands in the part's own .rels file so multiple sections can share the same media.",
    section: "Headers",
    surfaces: [],
  },
  {
    id: "docx.create-header-footer-part",
    commandType: "docx:create-header-footer-part",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Create header/footer part",
    description:
      "Mint a fresh header or footer part on the trailing section so the editor can drop the caret into a previously-empty zone (Word's double-click behavior).",
    section: "Headers",
    surfaces: [],
  },

  // ── Generic apply / pending ───────────────────────────────────────
  {
    id: "docx.apply",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Apply JSON commands",
    description:
      "Apply a JSON command file (single command or { commands: [...] }) and write the result. Pass -c/--commands to read from disk or --from-stdin to read JSON piped on stdin (mutually exclusive).",
    section: "Edit",
    surfaces: [],
    args: [
      {
        name: "file",
        flag: "--file <path>",
        kind: "filepath",
        required: true,
        description: "Path to a .docx file",
      },
      {
        name: "commands",
        flag: "-c, --commands <path>",
        kind: "filepath",
        description: "Path to a JSON file containing one or more commands",
      },
      {
        name: "fromStdin",
        flag: "--from-stdin",
        kind: "boolean",
        description: "Read the JSON command body from stdin instead of -c <path>",
      },
    ],
  },

  // ── Palette-only / non-mutating actions (UI surfaces) ─────────────
  // These wrap toolbar interactions so every toolbar button is also
  // discoverable via Cmd+K. They piggy-back on existing handlers
  // (apply-list-format, set-paragraph-alignment, set-paragraph-indent,
  // insert-section-break) that the CLI exposes via richer subcommands;
  // the palette versions take no arguments and operate on the current
  // selection.
  {
    id: "docx.bullet-list",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Bullet list",
    description: "Toggle a bullet list on the current paragraph.",
    section: "Lists",
    surfaces: ["palette"],
    icon: "List",
  },
  {
    id: "docx.ordered-list",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Numbered list",
    description: "Toggle a numbered list on the current paragraph.",
    section: "Lists",
    surfaces: ["palette"],
    icon: "ListOrdered",
  },
  {
    id: "docx.align-left",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Align left",
    description: "Left-align the current paragraph.",
    section: "Layout",
    surfaces: ["palette"],
    icon: "AlignLeft",
  },
  {
    id: "docx.align-center",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Align center",
    description: "Center-align the current paragraph.",
    section: "Layout",
    surfaces: ["palette"],
    icon: "AlignCenter",
  },
  {
    id: "docx.align-right",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Align right",
    description: "Right-align the current paragraph.",
    section: "Layout",
    surfaces: ["palette"],
    icon: "AlignRight",
  },
  {
    id: "docx.align-justify",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Justify",
    description: "Justify the current paragraph.",
    section: "Layout",
    surfaces: ["palette"],
    icon: "AlignJustify",
  },
  {
    id: "docx.indent-increase",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Increase indent",
    description: "Indent the current paragraph by one step (¼ inch).",
    section: "Layout",
    surfaces: ["palette"],
    icon: "Indent",
  },
  {
    id: "docx.indent-decrease",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Decrease indent",
    description: "Outdent the current paragraph by one step (¼ inch).",
    section: "Layout",
    surfaces: ["palette"],
    icon: "Outdent",
  },
  {
    id: "docx.section-break-next-page",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert section break (next page)",
    description: "Insert a next-page section break after the current paragraph.",
    section: "Layout",
    surfaces: ["palette"],
  },
  {
    id: "docx.section-break-continuous",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert section break (continuous)",
    description: "Insert a continuous section break after the current paragraph.",
    section: "Layout",
    surfaces: ["palette"],
  },
  {
    id: "docx.insert-table-3x3",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert table (3 × 3)",
    description: "Insert a 3 × 3 table at the current selection.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "docx.insert-table-2x2",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Insert table (2 × 2)",
    description: "Insert a 2 × 2 table at the current selection.",
    section: "Insert",
    surfaces: ["palette"],
  },
  {
    id: "docx.page-setup",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Page setup…",
    description: "Open the page setup dialog to configure margins, paper size, and orientation.",
    section: "Layout",
    surfaces: ["palette"],
  },
  {
    id: "docx.toggle-marks",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Toggle formatting marks",
    description: "Show or hide non-printing characters (paragraph marks, tabs, spaces).",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "docx.set-mode-edit",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Switch to Editing mode",
    description: "Direct edits commit to the document.",
    section: "Mode",
    surfaces: ["palette"],
  },
  {
    id: "docx.set-mode-suggest",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Switch to Suggesting mode",
    description: "Edits land as tracked changes for review.",
    section: "Mode",
    surfaces: ["palette"],
  },
  {
    id: "docx.set-mode-view",
    commandType: null,
    format: "docx",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Switch to Viewing mode",
    description: "Read-only mode — block all mutations.",
    section: "Mode",
    surfaces: ["palette"],
  },

  // ── Handlers without a public surface (still tracked) ─────────────
  // The bus exposes these handlers but the CLI / palette currently do
  // not — they are reached only via the `docx apply` JSON escape hatch
  // or via the in-editor dialogs that wrap them. The catalogue still
  // lists them so the parity check accepts the handler registration;
  // each entry carries a `hidden.reason` documenting why.
  {
    id: "docx.apply-list-format",
    commandType: "docx:apply-list-format",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Apply list format",
    description: "Toggle bullet/ordered list on a range (used by the toolbar list menu).",
    section: "Lists",
    surfaces: [],
    hidden: {
      reason:
        "Toolbar-only — invoked via the bullet/ordered-list menu in DocxEditor; CLI users compose set-list / remove-list directly.",
    },
  },
  {
    id: "docx.accept-all-changes",
    commandType: "docx:accept-all-changes",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Accept all changes",
    description: "Accept every pending tracked change in one mutation.",
    section: "Review",
    surfaces: ["palette", "toolbar"],
    icon: "CheckCheck",
    args: [],
    buildPayload: () => ({}),
  },
  {
    id: "docx.reject-all-changes",
    commandType: "docx:reject-all-changes",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Reject all changes",
    description: "Reject every pending tracked change in one mutation.",
    section: "Review",
    surfaces: ["palette", "toolbar"],
    icon: "X",
    args: [],
    buildPayload: () => ({}),
  },
  {
    id: "docx.insert-text-tracked",
    commandType: "docx:insert-text-tracked",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Insert text (tracked)",
    description: "Insert text as a tracked-change insertion (suggesting mode).",
    section: "Edit",
    surfaces: [],
    hidden: {
      reason:
        "Used implicitly when the editor is in suggesting mode; CLI users pick docx:insert-text directly.",
    },
  },
  {
    id: "docx.delete-range-tracked",
    commandType: "docx:delete-range-tracked",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete range (tracked)",
    description: "Delete a range as a tracked-change deletion (suggesting mode).",
    section: "Edit",
    surfaces: [],
    hidden: {
      reason:
        "Used implicitly when the editor is in suggesting mode; CLI users pick docx:delete-range directly.",
    },
  },
  {
    id: "docx.set-paragraph-spacing",
    commandType: "docx:set-paragraph-spacing",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set paragraph spacing",
    description: "Set line spacing / before / after on a paragraph.",
    section: "Layout",
    surfaces: [],
    hidden: {
      reason:
        "Wired to the toolbar spacing dropdown; CLI exposure is deferred until the flag matrix stabilises.",
    },
  },
  {
    id: "docx.insert-page-number",
    commandType: "docx:insert-page-number",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Insert page number",
    description: "Insert a page-number field into a header/footer paragraph at a flat-text byte offset.",
    section: "Insert",
    surfaces: ["palette", "toolbar"],
    icon: "Hash",
    args: [
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target header/footer paragraph id (use `docx inspect` to find ids)",
      },
      {
        name: "offset",
        flag: "--offset <n>",
        kind: "number",
        required: true,
        description: "0-based flat-text byte offset where the field should land",
      },
      {
        name: "field",
        flag: "--field <kind>",
        kind: "enum",
        choices: ["PAGE", "NUMPAGES"],
        default: "PAGE",
        description: "Field type — current page (PAGE) or total pages (NUMPAGES)",
      },
    ],
    buildPayload: ({ paragraphId, offset, field }) => ({
      paragraphId: String(paragraphId),
      offset: Number(offset),
      field: (field as string | undefined) ?? "PAGE",
    }),
  },
  {
    id: "docx.set-section-different-first",
    commandType: "docx:set-section-different-first",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set 'different first page'",
    description: "Toggle the first-page header/footer split on a section.",
    section: "Layout",
    surfaces: [],
    hidden: { reason: "Reached via the page-setup dialog; CLI exposure is deferred." },
  },
  {
    id: "docx.set-page-setup",
    commandType: "docx:set-page-setup",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Set page setup",
    description: "Update page size / margins / orientation on the section that owns a paragraph (in twips).",
    section: "Layout",
    surfaces: ["palette", "toolbar"],
    icon: "FileText",
    args: [
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based body block index inside the target section",
      },
      {
        name: "width",
        flag: "--width <twips>",
        kind: "number",
        description: "Page width in twips (1440 twips = 1 inch)",
      },
      { name: "height", flag: "--height <twips>", kind: "number", description: "Page height in twips" },
      {
        name: "orient",
        flag: "--orient <portrait|landscape>",
        kind: "enum",
        choices: ["portrait", "landscape"],
        description: "Page orientation",
      },
      { name: "top", flag: "--top <twips>", kind: "number", description: "Top margin in twips" },
      { name: "right", flag: "--right <twips>", kind: "number", description: "Right margin in twips" },
      { name: "bottom", flag: "--bottom <twips>", kind: "number", description: "Bottom margin in twips" },
      { name: "left", flag: "--left <twips>", kind: "number", description: "Left margin in twips" },
      { name: "header", flag: "--header <twips>", kind: "number", description: "Header offset in twips" },
      { name: "footer", flag: "--footer <twips>", kind: "number", description: "Footer offset in twips" },
      { name: "gutter", flag: "--gutter <twips>", kind: "number", description: "Gutter margin in twips" },
    ],
    buildPayload: (parsed) => buildSetPageSetupPayload(parsed),
  },
  {
    id: "docx.set-page-margins",
    commandType: "docx:set-page-setup",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Set page margins",
    description:
      "Set the top / right / bottom / left / header / footer / gutter margins (twips) on a section.",
    section: "Layout",
    surfaces: ["palette", "toolbar"],
    icon: "AlignJustify",
    args: [
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based body block index inside the target section",
      },
      { name: "top", flag: "--top <twips>", kind: "number", description: "Top margin in twips" },
      { name: "right", flag: "--right <twips>", kind: "number", description: "Right margin in twips" },
      { name: "bottom", flag: "--bottom <twips>", kind: "number", description: "Bottom margin in twips" },
      { name: "left", flag: "--left <twips>", kind: "number", description: "Left margin in twips" },
      { name: "header", flag: "--header <twips>", kind: "number", description: "Header offset in twips" },
      { name: "footer", flag: "--footer <twips>", kind: "number", description: "Footer offset in twips" },
      { name: "gutter", flag: "--gutter <twips>", kind: "number", description: "Gutter margin in twips" },
    ],
    buildPayload: (parsed) => {
      const payload = buildSetPageSetupPayload(parsed);
      if (!payload.pgMar) {
        throw new Error("set-page-margins requires at least one margin field");
      }
      return { paragraphIndex: payload.paragraphIndex, pgMar: payload.pgMar };
    },
  },
  {
    id: "docx.set-page-orientation",
    commandType: "docx:set-page-setup",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Set page orientation",
    description:
      "Set page orientation (portrait/landscape) on the section that owns a paragraph. Swaps width/height when needed.",
    section: "Layout",
    surfaces: ["palette", "toolbar"],
    icon: "RectangleHorizontal",
    args: [
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based body block index inside the target section",
      },
      {
        name: "orient",
        flag: "--orient <portrait|landscape>",
        kind: "enum",
        choices: ["portrait", "landscape"],
        required: true,
        description: "Page orientation",
      },
    ],
    buildPayload: ({ paragraphIndex, orient }) => ({
      paragraphIndex: Number(paragraphIndex),
      pgSz: { orient: String(orient) as "portrait" | "landscape" },
    }),
  },
  {
    id: "docx.set-page-size",
    commandType: "docx:set-page-setup",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Set page size",
    description:
      "Set the page width and height (in twips) on the section that owns a paragraph. 1440 twips = 1 inch.",
    section: "Layout",
    surfaces: ["palette", "toolbar"],
    icon: "Maximize",
    args: [
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based body block index inside the target section",
      },
      {
        name: "preset",
        flag: "--preset <name>",
        kind: "enum",
        choices: ["letter", "legal", "a4", "a3", "a5"],
        description: "Convenience preset (overridden by explicit --width/--height)",
      },
      { name: "width", flag: "--width <twips>", kind: "number", description: "Page width in twips" },
      { name: "height", flag: "--height <twips>", kind: "number", description: "Page height in twips" },
    ],
    buildPayload: ({ paragraphIndex, preset, width, height }) => {
      const presetSize = preset
        ? PAGE_SIZE_PRESETS[String(preset) as keyof typeof PAGE_SIZE_PRESETS]
        : undefined;
      const w = width !== undefined ? Number(width) : presetSize?.w;
      const h = height !== undefined ? Number(height) : presetSize?.h;
      if (w === undefined || h === undefined) {
        throw new Error("set-page-size requires either --preset or both --width and --height");
      }
      return {
        paragraphIndex: Number(paragraphIndex),
        pgSz: { w, h },
      };
    },
  },
  {
    id: "docx.set-image-properties",
    commandType: "docx:set-image-properties",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set image properties",
    description: "Update inline image alt text, name, or size.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via the image context toolbar; CLI exposure is deferred." },
  },
  {
    id: "docx.delete-image",
    commandType: "docx:delete-image",
    format: "docx",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete image",
    description: "Remove an inline image from a paragraph.",
    section: "Insert",
    surfaces: [],
    hidden: { reason: "Reached via the image context toolbar; CLI exposure is deferred." },
  },
  {
    id: "docx.insert-section-break",
    commandType: "docx:insert-section-break",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Insert section break",
    description: "Insert a section break (next page / continuous / even / odd) at a body-block index.",
    section: "Layout",
    surfaces: ["palette", "toolbar"],
    icon: "SeparatorHorizontal",
    args: [
      {
        name: "paragraphIndex",
        flag: "--paragraph-index <n>",
        kind: "number",
        required: true,
        description: "0-based body block index where the break should land (=== body length appends)",
      },
      {
        name: "type",
        flag: "--type <kind>",
        kind: "enum",
        choices: ["nextPage", "continuous", "evenPage", "oddPage"],
        default: "nextPage",
        description: "Section break type",
      },
    ],
    buildPayload: ({ paragraphIndex, type }) => ({
      paragraphIndex: Number(paragraphIndex),
      type: (type as string | undefined) ?? "nextPage",
    }),
  },
  {
    id: "docx.insert-page-break",
    commandType: "docx:insert-page-break",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Insert page break",
    description: "Splice a hard page break into a body paragraph at a flat-text byte offset.",
    section: "Layout",
    surfaces: ["palette", "toolbar"],
    icon: "FileText",
    args: [
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Target body paragraph id",
      },
      {
        name: "offset",
        flag: "--offset <n>",
        kind: "number",
        required: true,
        description: "0-based flat-text byte offset",
      },
    ],
    buildPayload: ({ paragraphId, offset }) => ({
      paragraphId: String(paragraphId),
      offset: Number(offset),
    }),
  },

  // ── Phase 3e — Table tools ───────────────────────────────────────
  {
    id: "docx.set-cell-shading",
    commandType: "docx:set-cell-shading",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Cell shading",
    description: "Set the background fill on a single table cell. Pass --fill null to clear.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "PaintBucket",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id.",
      },
      { name: "row", flag: "--row <n>", kind: "number", required: true, description: "0-based row index." },
      {
        name: "column",
        flag: "--column <n>",
        kind: "number",
        required: true,
        description: "0-based grid column index.",
      },
      {
        name: "fill",
        flag: "--fill <hex|null>",
        kind: "string",
        required: true,
        description: "Hex RGB color (e.g. FFE699), 'auto', or 'null' to clear.",
      },
      {
        name: "color",
        flag: "--color <hex>",
        kind: "string",
        description: "Optional pattern foreground color.",
      },
      {
        name: "pattern",
        flag: "--pattern <val>",
        kind: "string",
        description: "Optional shading pattern (clear/solid/pct25/...).",
      },
    ],
    buildPayload: (parsed) => {
      const fillRaw = String(parsed.fill);
      const fill = fillRaw === "null" ? null : fillRaw;
      const out: Record<string, unknown> = {
        tableId: String(parsed.tableId),
        row: Number(parsed.row),
        column: Number(parsed.column),
        fill,
      };
      if (parsed.color) out.color = String(parsed.color);
      if (parsed.pattern) out.pattern = String(parsed.pattern);
      return out;
    },
  },
  {
    id: "docx.set-cell-alignment",
    commandType: "docx:set-cell-alignment",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Cell vertical alignment",
    description: "Set the vertical alignment of a single table cell.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "AlignVerticalJustifyCenter",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id.",
      },
      { name: "row", flag: "--row <n>", kind: "number", required: true, description: "0-based row index." },
      {
        name: "column",
        flag: "--column <n>",
        kind: "number",
        required: true,
        description: "0-based grid column index.",
      },
      {
        name: "vAlign",
        flag: "--v-align <v>",
        kind: "enum",
        choices: ["top", "center", "bottom", "null"],
        required: true,
        description: "top | center | bottom — pass 'null' to clear.",
      },
    ],
    buildPayload: ({ tableId, row, column, vAlign }) => ({
      tableId: String(tableId),
      row: Number(row),
      column: Number(column),
      vAlign: String(vAlign) === "null" ? null : (String(vAlign) as "top"),
    }),
  },
  {
    id: "docx.set-row-height",
    commandType: "docx:set-row-height",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Row height",
    description: "Set a table row's height in twips. Pass --height-twips null to clear.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "MoveVertical",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id.",
      },
      { name: "row", flag: "--row <n>", kind: "number", required: true, description: "0-based row index." },
      {
        name: "heightTwips",
        flag: "--height-twips <n|null>",
        kind: "string",
        required: true,
        description: "Row height in twips, or 'null' to clear.",
      },
      {
        name: "rule",
        flag: "--rule <r>",
        kind: "enum",
        choices: ["auto", "exact", "atLeast"],
        description: "Row-height rule.",
      },
    ],
    buildPayload: ({ tableId, row, heightTwips, rule }) => {
      const raw = String(heightTwips);
      const out: Record<string, unknown> = {
        tableId: String(tableId),
        row: Number(row),
        heightTwips: raw === "null" ? null : Number(raw),
      };
      if (rule) out.rule = String(rule);
      return out;
    },
  },
  {
    id: "docx.set-column-width",
    commandType: "docx:set-column-width",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Column width",
    description: "Set a table column's width in twips (1440 twips = 1 inch).",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "MoveHorizontal",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id.",
      },
      {
        name: "column",
        flag: "--column <n>",
        kind: "number",
        required: true,
        description: "0-based grid column index.",
      },
      {
        name: "widthTwips",
        flag: "--width-twips <n>",
        kind: "number",
        required: true,
        description: "Column width in twips.",
      },
    ],
    buildPayload: ({ tableId, column, widthTwips }) => ({
      tableId: String(tableId),
      column: Number(column),
      widthTwips: Number(widthTwips),
    }),
  },
  {
    id: "docx.merge-cells-horizontal",
    commandType: "docx:merge-cells-horizontal",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Merge cells (horizontal)",
    description: "Merge a contiguous run of cells in a single row into one cell with gridSpan.",
    section: "Tables",
    surfaces: ["palette", "toolbar", "contextMenu"],
    icon: "TableCellsMerge",
    args: [
      {
        name: "tableId",
        flag: "--table-id <id>",
        kind: "string",
        required: true,
        description: "Target table id.",
      },
      { name: "row", flag: "--row <n>", kind: "number", required: true, description: "0-based row index." },
      {
        name: "fromColumn",
        flag: "--from-column <n>",
        kind: "number",
        required: true,
        description: "0-based starting grid column.",
      },
      {
        name: "toColumn",
        flag: "--to-column <n>",
        kind: "number",
        required: true,
        description: "0-based ending grid column (inclusive).",
      },
    ],
    buildPayload: ({ tableId, row, fromColumn, toColumn }) => ({
      tableId: String(tableId),
      row: Number(row),
      fromColumn: Number(fromColumn),
      toColumn: Number(toColumn),
    }),
  },

  // ── Phase 6 — Protection ─────────────────────────────────────────
  {
    id: "docx.set-protection",
    commandType: "docx:set-protection",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Restrict editing",
    description:
      "Toggle Word's Restrict Editing element in word/settings.xml. Pass --enabled false to clear; precomputed password hashes are accepted via --password-hash + --algorithm-name + --salt-value + --spin-count.",
    section: "Review",
    surfaces: ["palette", "toolbar"],
    icon: "Lock",
    args: [
      {
        name: "enabled",
        flag: "--enabled <bool>",
        kind: "boolean",
        default: true,
        description: "true to enable protection, false to clear.",
      },
      {
        name: "edit",
        flag: "--edit <kind>",
        kind: "enum",
        choices: ["readOnly", "comments", "trackedChanges", "forms", "none"],
        description: "Allowed edit type when protection is on.",
        default: "readOnly",
      },
      {
        name: "enforce",
        flag: "--enforce <bool>",
        kind: "boolean",
        default: true,
        description: "Whether the protection is enforced (Word may otherwise treat it as a recommendation).",
      },
      {
        name: "formatting",
        flag: "--formatting <bool>",
        kind: "boolean",
        description: "Restrict formatting changes too.",
      },
      {
        name: "passwordHash",
        flag: "--password-hash <hex>",
        kind: "string",
        description: "Precomputed password hash.",
      },
      {
        name: "algorithmName",
        flag: "--algorithm-name <name>",
        kind: "string",
        description: "Hash algorithm name.",
      },
      { name: "saltValue", flag: "--salt-value <b64>", kind: "string", description: "Salt for the hash." },
      { name: "spinCount", flag: "--spin-count <n>", kind: "number", description: "Iteration count." },
    ],
    buildPayload: (parsed) => {
      const out: Record<string, unknown> = {
        enabled: parsed.enabled === false || parsed.enabled === "false" ? false : true,
      };
      if (parsed.edit) out.edit = String(parsed.edit);
      if (parsed.enforce !== undefined) out.enforce = parsed.enforce !== false && parsed.enforce !== "false";
      if (parsed.formatting !== undefined)
        out.formatting = parsed.formatting !== false && parsed.formatting !== "false";
      if (parsed.passwordHash) out.passwordHash = String(parsed.passwordHash);
      if (parsed.algorithmName) out.algorithmName = String(parsed.algorithmName);
      if (parsed.saltValue) out.saltValue = String(parsed.saltValue);
      if (parsed.spinCount !== undefined) out.spinCount = Number(parsed.spinCount);
      return out;
    },
  },

  // ── Phase 9d — References tab: bookmarks ─────────────────────────
  {
    id: "docx.insert-bookmark",
    commandType: "docx:insert-bookmark",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Insert bookmark",
    description:
      "Word's References > Bookmark dialog. Anchors a <w:bookmarkStart>/<w:bookmarkEnd> pair at flat-text byte offsets inside the named paragraph. `name` must match Word's identifier rules ([A-Za-z_][\\w]*). Pass equal start/end offsets for a zero-length anchor.",
    section: "References",
    surfaces: ["palette", "toolbar"],
    icon: "Bookmark",
    args: [
      {
        name: "name",
        flag: "--name <id>",
        kind: "string",
        required: true,
        description: "Bookmark name (identifier).",
      },
      {
        name: "paragraphId",
        flag: "--paragraph-id <id>",
        kind: "string",
        required: true,
        description: "Body paragraph that will host the anchor pair.",
      },
      {
        name: "startOffset",
        flag: "--start-offset <n>",
        kind: "number",
        required: true,
        description: "Flat-text byte offset where the bookmark starts.",
      },
      {
        name: "endOffset",
        flag: "--end-offset <n>",
        kind: "number",
        required: true,
        description: "Flat-text byte offset where the bookmark ends (>= start).",
      },
    ],
    buildPayload: (parsed) => ({
      name: String(parsed.name),
      paragraphId: String(parsed.paragraphId),
      startOffset: Number(parsed.startOffset),
      endOffset: Number(parsed.endOffset),
    }),
  },
  {
    id: "docx.delete-bookmark",
    commandType: "docx:delete-bookmark",
    format: "docx",
    agentCallable: true,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "catalogue-args",
    label: "Delete bookmark",
    description:
      "Strip every <w:bookmarkStart>/<w:bookmarkEnd> anchor pair carrying the given name. Idempotent.",
    section: "References",
    surfaces: ["palette", "toolbar"],
    icon: "Trash2",
    args: [
      {
        name: "name",
        flag: "--name <id>",
        kind: "string",
        required: true,
        description: "Bookmark name to remove.",
      },
    ],
    buildPayload: (parsed) => ({ name: String(parsed.name) }),
  },
];
