import * as React from "react";
import type { ChartPart, Slide, SlideSize, ThemeColorScheme } from "../../model/types.js";
import { slideAspectRatio } from "../layout/slide.js";
import { slideToSvgString } from "../svg/slide.js";
import type { SvgRenderCtx } from "../svg/shapes.js";

export interface SlideThumbnailProps {
  readonly slide: Slide;
  readonly slideSize: SlideSize;
  readonly mediaUrls?: ReadonlyMap<string, string>;
  readonly theme?: ThemeColorScheme;
  readonly charts?: ReadonlyMap<string, ChartPart>;
  readonly width?: number;
  readonly active?: boolean;
  readonly onClick?: () => void;
  readonly label?: string;
}

/**
 * Non-interactive miniature of a slide. Inlines an SVG generated by
 * `slideToSvgString` for SSR-safety and zero React reconciliation cost
 * inside the slide.
 */
export function SlideThumbnail(props: SlideThumbnailProps): React.ReactElement {
  const { slide, slideSize, mediaUrls, theme, charts, width = 200, active, onClick, label } = props;
  const ctx: SvgRenderCtx = {
    slideSize,
    mediaUrls,
    ...(theme ? { theme } : {}),
    ...(charts ? { charts } : {}),
  };
  const aspect = slideAspectRatio(slideSize);
  const svg = React.useMemo(() => slideToSvgString(slide, ctx), [slide, slideSize, mediaUrls, theme, charts]);

  return (
    <button
      type="button"
      onClick={onClick}
      // Safari and Firefox on macOS don't focus <button> on mouse
      // click by default — only Tab focus works. We force focus on
      // pointer-down so downstream consumers (e.g. the PPTX sidebar's
      // Delete-to-remove-slide handler) can rely on
      // `document.activeElement` / `event.target` actually pointing
      // at the clicked thumbnail.
      onMouseDown={(e) => {
        e.currentTarget.focus({ preventScroll: true });
      }}
      className={["officeai-pptx-thumb", active ? "officeai-pptx-thumb--active" : ""]
        .filter(Boolean)
        .join(" ")}
      style={{
        width,
        aspectRatio: String(aspect),
        padding: 0,
        border: active ? "2px solid var(--ai-violet, #7c3aed)" : "1px solid #e4e4e7",
        background: "#fff",
        cursor: "pointer",
        overflow: "hidden",
        display: "block",
      }}
      aria-label={label ?? `Slide ${slide.slideId}`}
    >
      <span
        style={{ display: "block", width: "100%", height: "100%" }}
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </button>
  );
}
