/* eslint-disable react/no-danger */
import * as React from "react";
import type { Slide, SlideSize } from "../../model/types.js";
import { slideAspectRatio } from "../layout/slide.js";
import { slideToSvgString } from "../svg/slide.js";
import type { SvgRenderCtx } from "../svg/shapes.js";

export interface SlideThumbnailProps {
  readonly slide: Slide;
  readonly slideSize: SlideSize;
  readonly mediaUrls?: ReadonlyMap<string, string>;
  readonly width?: number;
  readonly active?: boolean;
  readonly onClick?: () => void;
  readonly label?: string;
}

/**
 * Non-interactive miniature of a slide. Inlines an SVG generated by
 * `slideToSvgString` for SSR-safety and zero React reconciliation cost
 * inside the slide.
 */
export function SlideThumbnail(props: SlideThumbnailProps): React.ReactElement {
  const { slide, slideSize, mediaUrls, width = 200, active, onClick, label } = props;
  const ctx: SvgRenderCtx = { slideSize, mediaUrls };
  const aspect = slideAspectRatio(slideSize);
  const svg = React.useMemo(() => slideToSvgString(slide, ctx), [slide, slideSize, mediaUrls]);

  return (
    <button
      type="button"
      onClick={onClick}
      className={[
        "officeai-pptx-thumb",
        active ? "officeai-pptx-thumb--active" : "",
      ]
        .filter(Boolean)
        .join(" ")}
      style={{
        width,
        aspectRatio: String(aspect),
        padding: 0,
        border: active ? "2px solid var(--ai-violet, #7c3aed)" : "1px solid #e4e4e7",
        background: "#fff",
        cursor: "pointer",
        overflow: "hidden",
        display: "block",
      }}
      aria-label={label ?? `Slide ${slide.slideId}`}
    >
      <span
        style={{ display: "block", width: "100%", height: "100%" }}
        dangerouslySetInnerHTML={{ __html: svg }}
      />
    </button>
  );
}
