/**
 * Action catalogue for PDF. Single source of truth tying together
 * each command-bus handler, its agent/CLI callability, and web
 * surfaces.
 *
 * Note: the PDF surface is split. Some `office-agent pdf …`
 * subcommands ride the bus (rotate-pages, delete-pages, …); others
 * (merge, split, fill-form, add-watermark) live in `pdf-edit` /
 * `pdf-forms` / `pdf-ocr` and run directly on the input bytes
 * because they aren't yet modelled as bus commands. The catalogue
 * tracks both so the parity check can validate every public
 * affordance has a known home, while marking the non-bus ones with
 * `commandType: null` and `commandSchema: "none"`.
 */

import type { ActionDescriptor } from "@officeai/core";

export const pdfActions: ReadonlyArray<ActionDescriptor> = [
  // ── Read (no commandType) ─────────────────────────────────────────
  {
    id: "pdf.read-metadata",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Read metadata",
    description: "Print the PDF's document-info dictionary, page count, and engine details.",
    section: "Read",
    surfaces: [],
  },
  {
    id: "pdf.read-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Read page",
    description: "Read a single page's text content.",
    section: "Read",
    surfaces: [],
  },
  {
    id: "pdf.read-outline",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Read outline",
    description: "Print the document outline (bookmarks) as JSON.",
    section: "Read",
    surfaces: [],
  },
  {
    id: "pdf.read-annotations",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Read annotations",
    description: "List every annotation across the document as JSON.",
    section: "Read",
    surfaces: [],
  },
  {
    id: "pdf.list-form-fields",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "List form fields",
    description: "List every interactive form field with its current value.",
    section: "Read",
    surfaces: [],
  },
  {
    id: "pdf.search-text",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Search text",
    description: "Search the PDF's text layer; emits matches as JSON.",
    section: "Read",
    surfaces: [],
  },
  {
    id: "pdf.export-markdown",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Export Markdown",
    description: "Project the PDF's text content as Markdown.",
    section: "Read",
    surfaces: [],
  },

  // ── Page-level mutations (bus-backed) ─────────────────────────────
  {
    id: "pdf.rotate-pages",
    commandType: "pdf:rotate-pages",
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Rotate pages",
    description: "Rotate one or more pages by 90/180/270°.",
    section: "Pages",
    surfaces: ["palette"],
    icon: "RotateCw",
  },
  {
    id: "pdf.set-page-rotation",
    commandType: "pdf:set-page-rotation",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set page rotation",
    description: "Set absolute rotation on a single page.",
    section: "Pages",
    surfaces: ["palette"],
    hidden: { reason: "Wrapped by pdf rotate-pages on the CLI; surfaced separately in the palette." },
  },
  {
    id: "pdf.reorder-pages",
    commandType: "pdf:reorder-pages",
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Reorder pages",
    description: "Reorder the document's pages.",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.delete-pages",
    commandType: "pdf:delete-pages",
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete pages",
    description: "Delete one or more pages from the document.",
    section: "Pages",
    surfaces: ["palette"],
  },

  // ── Page-level mutations (pdf-edit; not yet bus-backed) ───────────
  {
    id: "pdf.merge",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Merge PDFs",
    description: "Merge two or more PDFs in order; writes a new PDF to --out.",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.split",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Split PDF",
    description: "Split a PDF by page range or every-N-pages; writes one PDF per chunk.",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.extract-pages",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Extract pages",
    description: "Extract a page range into a new PDF.",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.crop-pages",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Crop pages",
    description: "Crop a page range to a rectangle.",
    section: "Pages",
    surfaces: [],
  },
  {
    id: "pdf.add-watermark",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Add watermark",
    description: "Stamp a text or image watermark across a page range.",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.add-page-numbers",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Add page numbers",
    description: "Stamp page numbers across a page range.",
    section: "Pages",
    surfaces: ["palette"],
  },

  // ── Metadata ──────────────────────────────────────────────────────
  {
    id: "pdf.set-metadata",
    commandType: "pdf:set-metadata",
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Set metadata",
    description: "Set / clear metadata fields (title, author, subject, keywords).",
    section: "Document",
    surfaces: ["palette"],
  },

  // ── Bookmarks ─────────────────────────────────────────────────────
  {
    id: "pdf.add-bookmark",
    commandType: "pdf:add-bookmark",
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Add bookmark",
    description: "Add a bookmark / outline entry to the document.",
    section: "Document",
    // Phase 9d: now wired in PdfSidebar's outline tab (the "+"
    // affordance) and PdfToolbar (icon button); also reachable from
    // Cmd+K. CLI exposure stays deferred — the parent/child outline
    // tree shape needs a dedicated CLI argument schema we haven't
    // designed yet.
    surfaces: ["palette"],
  },

  // ── Annotations ───────────────────────────────────────────────────
  {
    id: "pdf.add-annotation",
    commandType: "pdf:add-annotation",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Add annotation",
    description: "Add an annotation (highlight / underline / text / shape) to a page.",
    section: "Annotations",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the annotation toolbar; CLI exposure is deferred." },
  },
  {
    id: "pdf.update-annotation",
    commandType: "pdf:update-annotation",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Update annotation",
    description: "Update an annotation's color / text / geometry.",
    section: "Annotations",
    surfaces: [],
    hidden: { reason: "Reached via the annotation property pane." },
  },
  {
    id: "pdf.remove-annotation",
    commandType: "pdf:remove-annotation",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Remove annotation",
    description: "Remove an annotation.",
    section: "Annotations",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the annotation context menu." },
  },

  // ── Comments (bus-backed, share annotation surface) ───────────────
  {
    id: "pdf.add-comment",
    commandType: "pdf:add-comment",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Add comment",
    description: "Anchor a sticky-note comment to a page.",
    section: "Comments",
    surfaces: ["palette"],
    hidden: { reason: "Reached via the comment toolbar; CLI exposure is deferred." },
  },
  {
    id: "pdf.reply-comment",
    commandType: "pdf:reply-comment",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Reply to comment",
    description: "Append a reply to an existing comment thread.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },
  {
    id: "pdf.edit-comment",
    commandType: "pdf:edit-comment",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Edit comment",
    description: "Edit a comment's text.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },
  {
    id: "pdf.resolve-comment",
    commandType: "pdf:resolve-comment",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Resolve comment",
    description: "Mark a comment thread as resolved.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },
  {
    id: "pdf.delete-comment",
    commandType: "pdf:delete-comment",
    format: "pdf",
    agentCallable: false,
    webCallable: false,
    cliCallable: false,
    requiresReview: true,
    supportsDryRun: false,
    supportsDiff: true,
    commandSchema: "custom",
    label: "Delete comment",
    description: "Delete a comment thread.",
    section: "Comments",
    surfaces: [],
    hidden: { reason: "Reached via the comment thread UI." },
  },

  // ── Forms ─────────────────────────────────────────────────────────
  {
    id: "pdf.fill-form",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Fill form",
    description: "Fill an interactive form from a JSON map of field → value.",
    section: "Forms",
    surfaces: ["palette"],
  },
  {
    id: "pdf.flatten-form",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Flatten form",
    description: "Flatten an interactive form into static PDF content.",
    section: "Forms",
    surfaces: ["palette"],
  },
  {
    id: "pdf.reset-form",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Reset form",
    description: "Reset every interactive form field to its default value.",
    section: "Forms",
    surfaces: ["palette"],
  },

  // ── OCR ───────────────────────────────────────────────────────────
  {
    id: "pdf.add-text-layer",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: true,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Add OCR text layer",
    description: "Run OCR over each page and embed an invisible selectable text layer.",
    section: "OCR",
    surfaces: ["palette"],
  },

  // ── Palette-only viewer sugar (navigation + zoom + display) ───────
  // These are local viewer state changes; no command-bus mutation is
  // involved. They live in the catalogue so Cmd+K stays the single
  // surface for everything the user can reach from a UI button.
  {
    id: "pdf.next-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Next page",
    description: "Navigate to the next page in the viewer.",
    section: "Navigate",
    surfaces: ["palette"],
  },
  {
    id: "pdf.prev-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Previous page",
    description: "Navigate to the previous page in the viewer.",
    section: "Navigate",
    surfaces: ["palette"],
  },
  {
    id: "pdf.first-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "First page",
    description: "Jump to the first page.",
    section: "Navigate",
    surfaces: ["palette"],
  },
  {
    id: "pdf.last-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Last page",
    description: "Jump to the last page.",
    section: "Navigate",
    surfaces: ["palette"],
  },
  {
    id: "pdf.zoom-in",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Zoom in",
    description: "Increase the viewer zoom level.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.zoom-out",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Zoom out",
    description: "Decrease the viewer zoom level.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.fit-width",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Fit width",
    description: "Fit the page width to the viewer.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.fit-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Fit page",
    description: "Fit a whole page into the viewer.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.actual-size",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Actual size (100 %)",
    description: "Reset the viewer zoom to 100%.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.rotate-cw",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Rotate view clockwise",
    description: "Rotate the on-screen view clockwise (does not modify the PDF).",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.rotate-ccw",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Rotate view counter-clockwise",
    description: "Rotate the on-screen view counter-clockwise (does not modify the PDF).",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.toggle-dark",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Toggle dark mode",
    description: "Cycle the viewer through light, sepia, and dark display modes.",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.toggle-reflow",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Toggle reflow",
    description: "Toggle reflowed reading mode (single-column text reflow).",
    section: "View",
    surfaces: ["palette"],
  },
  {
    id: "pdf.rotate-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Rotate current page 90°",
    description: "Rotate the current page by 90° (writes to the document; see also pdf.rotate-pages).",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.delete-page",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Delete current page",
    description: "Delete the current page from the document (see also pdf.delete-pages).",
    section: "Pages",
    surfaces: ["palette"],
  },
  {
    id: "pdf.print",
    commandType: null,
    format: "pdf",
    agentCallable: false,
    webCallable: true,
    cliCallable: false,
    requiresReview: false,
    supportsDryRun: false,
    supportsDiff: false,
    commandSchema: "none",
    label: "Print…",
    description: "Open the browser's native print dialog for the PDF.",
    section: "File",
    surfaces: ["palette"],
  },
];
