/**
 * GET /api/sessions/:documentId/projection
 *
 * Path-free web projection over the persisted working artifact. The payload is
 * generated by @officeai/agent/projections, the same projection module used by
 * the MCP document projection tool.
 */

import { NextResponse } from "next/server";
import { createLocalSessionStore, SessionStoreCorruptError } from "@officeai/agent/session-store";
import {
  projectOfficeDocument,
  type ProjectionKind,
  type ProjectionSource,
} from "@officeai/agent/projections";
import { projectionSourceFromBytes } from "@/lib/sessions/server-documents";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

export async function GET(
  request: Request,
  context: { readonly params: Promise<{ readonly documentId: string }> }
): Promise<NextResponse> {
  try {
    const { documentId } = await context.params;
    const url = new URL(request.url);
    const projection = parseProjection(url.searchParams.get("projection"));
    if (!projection) {
      return badRequest(
        "unsupported-projection",
        "projection must be summary, markdown, json, text or page."
      );
    }

    const opts = parseProjectionOptions(url.searchParams);
    if ("error" in opts) return badRequest(opts.error.code, opts.error.message);

    const store = createLocalSessionStore();
    const document = await store.getDocument(documentId);
    if (!document) {
      return NextResponse.json(
        {
          schema: "office-ai/web-sessions-error@1",
          code: "document-not-found",
          message: `Document ${documentId} was not found in the local workspace.`,
        },
        { status: 404 }
      );
    }

    const expectedRevision = parseOptionalInteger(url.searchParams.get("revision"));
    if (Number.isNaN(expectedRevision)) {
      return badRequest("invalid-revision", "revision must be an integer.");
    }
    if (expectedRevision !== undefined && expectedRevision !== document.revision) {
      return NextResponse.json(
        {
          schema: "office-ai/web-sessions-error@1",
          code: "stale-revision",
          message: `Projection requested revision ${expectedRevision}, but ${document.id} is at revision ${document.revision}.`,
          documentId: document.id,
          expectedRevision,
          actualRevision: document.revision,
        },
        { status: 409 }
      );
    }

    const bytes = await store.readWorkingBytes(document);
    const source = await projectionSourceFromBytes(document.format, bytes);
    const anchor = url.searchParams.get("anchor");
    if (anchor) {
      const anchorResult = validateAnchor(source, anchor);
      if (!anchorResult.ok) {
        return NextResponse.json(
          {
            schema: "office-ai/web-sessions-error@1",
            code: anchorResult.code,
            message: anchorResult.message,
            documentId: document.id,
            anchor,
          },
          { status: anchorResult.status }
        );
      }
    }
    return NextResponse.json(
      projectOfficeDocument(
        {
          documentId: document.id,
          sessionId: document.sessionId,
          format: document.format,
          name: document.name,
          status: document.status,
          revision: document.revision,
          diagnostics: document.diagnostics,
          exportHistory: document.exportHistory.map((entry) => ({
            bytes: entry.bytes,
            exportedAt: entry.exportedAt,
          })),
          createdAt: document.createdAt,
          updatedAt: document.updatedAt,
        },
        source,
        { projection, ...opts.value }
      )
    );
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (err instanceof SessionStoreCorruptError) {
      return NextResponse.json(
        {
          schema: "office-ai/web-sessions-error@1",
          code: "corrupt-session-store",
          message,
        },
        { status: 409 }
      );
    }
    return NextResponse.json(
      {
        schema: "office-ai/web-sessions-error@1",
        code: "session-projection-error",
        message,
      },
      { status: 500 }
    );
  }
}

function badRequest(code: string, message: string): NextResponse {
  return NextResponse.json(
    {
      schema: "office-ai/web-sessions-error@1",
      code,
      message,
    },
    { status: 400 }
  );
}

function parseProjection(value: string | null): ProjectionKind | null {
  if (value === null || value === "") return "markdown";
  if (
    value === "summary" ||
    value === "markdown" ||
    value === "json" ||
    value === "text" ||
    value === "page"
  ) {
    return value;
  }
  return null;
}

function parseProjectionOptions(params: URLSearchParams):
  | {
      readonly value: {
        readonly page?: number;
        readonly sheet?: string;
        readonly range?: string;
        readonly slide?: number;
        readonly maxRows?: number;
        readonly maxCols?: number;
      };
    }
  | { readonly error: { readonly code: string; readonly message: string } } {
  const page = parseOptionalInteger(params.get("page"));
  const slide = parseOptionalInteger(params.get("slide"));
  const maxRows = parseOptionalInteger(params.get("max_rows"));
  const maxCols = parseOptionalInteger(params.get("max_cols"));
  if (Number.isNaN(page)) {
    return { error: { code: "invalid-page", message: "page must be an integer." } };
  }
  if (Number.isNaN(slide)) {
    return { error: { code: "invalid-slide", message: "slide must be an integer." } };
  }
  if (Number.isNaN(maxRows)) {
    return { error: { code: "invalid-max-rows", message: "max_rows must be an integer." } };
  }
  if (Number.isNaN(maxCols)) {
    return { error: { code: "invalid-max-cols", message: "max_cols must be an integer." } };
  }
  if (page !== undefined && page < 1) {
    return { error: { code: "invalid-page", message: "page must be a positive 1-based integer." } };
  }
  if (slide !== undefined && slide < 0) {
    return { error: { code: "invalid-slide", message: "slide must be a zero-based integer." } };
  }
  if (maxRows !== undefined && maxRows < 1) {
    return { error: { code: "invalid-max-rows", message: "max_rows must be positive." } };
  }
  if (maxCols !== undefined && maxCols < 1) {
    return { error: { code: "invalid-max-cols", message: "max_cols must be positive." } };
  }
  return {
    value: {
      ...(page !== undefined ? { page } : {}),
      ...(params.get("sheet") ? { sheet: params.get("sheet") ?? undefined } : {}),
      ...(params.get("range") ? { range: params.get("range") ?? undefined } : {}),
      ...(slide !== undefined ? { slide } : {}),
      ...(maxRows !== undefined ? { maxRows } : {}),
      ...(maxCols !== undefined ? { maxCols } : {}),
    },
  };
}

function parseOptionalInteger(value: string | null): number | undefined {
  if (value === null || value.trim() === "") return undefined;
  const n = Number(value);
  return Number.isInteger(n) ? n : Number.NaN;
}

function validateAnchor(
  source: ProjectionSource,
  anchor: string
):
  | { readonly ok: true }
  | { readonly ok: false; readonly status: number; readonly code: string; readonly message: string } {
  const [kind, rawValue] = anchor.split(/:(.*)/s);
  if (!kind || rawValue === undefined || rawValue.length === 0) {
    return {
      ok: false,
      status: 400,
      code: "invalid-anchor",
      message: "anchor must use '<kind>:<value>' format.",
    };
  }
  switch (source.format) {
    case "docx": {
      if (kind !== "paragraph") return invalidAnchorKind("DOCX anchors use paragraph:<index>.");
      const index = Number(rawValue);
      const block = Number.isInteger(index) ? source.agent.getSnapshot().root.body[index] : undefined;
      return block?.kind === "paragraph" ? { ok: true } : anchorNotFound(anchor);
    }
    case "xlsx": {
      if (kind !== "sheet") return invalidAnchorKind("XLSX anchors use sheet:<name>.");
      return source.agent.getSnapshot().root.sheets.some((sheet) => sheet.name === rawValue)
        ? { ok: true }
        : anchorNotFound(anchor);
    }
    case "pptx": {
      if (kind !== "slide") return invalidAnchorKind("PPTX anchors use slide:<index>.");
      const index = Number(rawValue);
      return Number.isInteger(index) && source.agent.getSnapshot().root.slides[index]
        ? { ok: true }
        : anchorNotFound(anchor);
    }
    case "pdf": {
      if (kind !== "page") return invalidAnchorKind("PDF anchors use page:<number>.");
      const page = Number(rawValue);
      return Number.isInteger(page) && page >= 1 && page <= source.agent.getSnapshot().root.pages.length
        ? { ok: true }
        : anchorNotFound(anchor);
    }
  }
}

function invalidAnchorKind(message: string): {
  readonly ok: false;
  readonly status: number;
  readonly code: string;
  readonly message: string;
} {
  return { ok: false, status: 400, code: "invalid-anchor-kind", message };
}

function anchorNotFound(anchor: string): {
  readonly ok: false;
  readonly status: number;
  readonly code: string;
  readonly message: string;
} {
  return { ok: false, status: 404, code: "anchor-not-found", message: `Anchor ${anchor} was not found.` };
}
